# -*- coding: utf-8 -*-
"""
add_top_categories.py — adauga categorii noi in frontend/public/top-produse.json
Ruleaza din scripts/:  python add_top_categories.py
Idempotent: nu dubleaza categorii cu acelasi slug.
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(ROOT, "frontend", "public", "top-produse.json")


def mag(slug, eticheta, pret, recomandat=False):
    return {"magazin_slug": slug, "eticheta": eticheta, "pret": pret, "recomandat": recomandat}


def prod(pozitie, badge, badge_color, nume, model, seed, pret, scor, scoruri, verdict_scurt,
         verdict_detaliat, pro, contra, specificatii, magazine):
    return {
        "pozitie": pozitie, "badge": badge, "badge_color": badge_color,
        "nume": nume, "model": model,
        "imagine": f"https://picsum.photos/seed/{seed}/400/280",
        "pret_de_la": pret, "moneda": "RON", "scor_total": scor,
        "scoruri": scoruri, "verdict_scurt": verdict_scurt, "verdict_detaliat": verdict_detaliat,
        "pro": pro, "contra": contra, "specificatii": specificatii, "magazine": magazine,
    }


NEW_CATEGORIES = []

# ── parfumuri-femei ──────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "parfumuri-femei", "titlu": "Cele mai bune parfumuri de dama 2026",
    "titlu_scurt": "Parfumuri femei", "emoji": "💐", "culoare": "pink", "tag": "TOP VANZARI",
    "descriere": "Am testat 25+ parfumuri de dama. Top 5 dupa persistenta, sillage si raport pret/calitate, de la floral la oriental.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Lancome La Vie Est Belle", "EDP 75ml", "lvieb", 389, 9.5,
             {"Persistenta": 9.4, "Sillage": 9.0, "Versatilitate": 9.6, "Ambalaj": 9.5, "Pret/Calitate": 9.2},
             "Cel mai versatil parfum floral-gourmand pentru orice ocazie",
             "La Vie Est Belle ramane referinta categoriei floral-gourmand: iris, paciuli si vanilie intr-un sillage cald, feminin, potrivit zi si seara. Persistenta de 8-10 ore il face un cumparat sigur.",
             ["Persistenta excelenta 8-10h", "Versatil zi/seara", "Flacon iconic reutilizabil", "Compliment magnet"],
             ["Pret premium", "Dulce pentru sezonul cald", "Foarte raspandit"],
             {"Familie olfactiva": "Floral gourmand", "Note de varf": "Coacaze negre, para", "Note de baza": "Vanilie, paciuli, tonka", "Concentratie": "Eau de Parfum", "Volum": "75 ml"},
             [mag("notino.ro", "Notino", 389, True), mag("douglas.ro", "Douglas", 419), mag("emag.ro", "eMAG", 435)]),
        prod(2, "Cel mai bun raport pret", "green", "Yves Saint Laurent Libre", "EDP 90ml", "yslibre", 449, 9.3,
             {"Persistenta": 9.2, "Sillage": 9.4, "Versatilitate": 9.0, "Ambalaj": 9.3, "Pret/Calitate": 9.1},
             "Lavanda si floare de portocal intr-un parfum modern, indraznet",
             "Libre combina lavanda masculina cu floarea de portocal feminina, rezultand un parfum modern, energic, cu sillage puternic. Ideal pentru femeia activa care vrea sa fie remarcata.",
             ["Sillage puternic", "Note unisex moderne", "Persistenta 8h+", "Flacon elegant"],
             ["Intens pentru birou", "Pret ridicat"],
             {"Familie olfactiva": "Floral lavanda", "Note de varf": "Mandarina, coacaze", "Note de baza": "Vanilie de Madagascar, ambra", "Concentratie": "Eau de Parfum", "Volum": "90 ml"},
             [mag("notino.ro", "Notino", 449, True), mag("sephora.ro", "Sephora", 489), mag("douglas.ro", "Douglas", 475)]),
        prod(3, "Cel mai bun pentru zi", "blue", "Chloe Eau de Parfum", "EDP 75ml", "chloeedp", 359, 9.1,
             {"Persistenta": 8.8, "Sillage": 8.6, "Versatilitate": 9.4, "Ambalaj": 9.2, "Pret/Calitate": 9.0},
             "Trandafir pudrat, elegant, perfect pentru birou si zi",
             "Chloe EDP este un floral-pudrat rafinat, dominat de trandafir si bujor, cu un finish de musk curat. Discret dar feminin, ideal pentru purtare zilnica si mediul profesional.",
             ["Elegant si discret", "Perfect pentru birou", "Flacon clasic frumos", "Placut universal"],
             ["Persistenta medie 6h", "Mai putin remarcabil seara"],
             {"Familie olfactiva": "Floral", "Note de varf": "Bujor, freesia", "Note de baza": "Cedru, musc, amber", "Concentratie": "Eau de Parfum", "Volum": "75 ml"},
             [mag("notino.ro", "Notino", 359, True), mag("douglas.ro", "Douglas", 389), mag("marionnaud.ro", "Marionnaud", 379)]),
        prod(4, "Cel mai seducator", "purple", "Carolina Herrera Good Girl", "EDP 80ml", "ggirl", 419, 9.0,
             {"Persistenta": 9.3, "Sillage": 9.1, "Versatilitate": 8.5, "Ambalaj": 9.6, "Pret/Calitate": 8.8},
             "Iasomie si boabe de tonka, intens si seducator pentru seara",
             "Good Girl, in flaconul iconic in forma de pantof, este un parfum oriental-floral intens, cu iasomie si tonka, gandit pentru serile lungi. Sillage si persistenta de top.",
             ["Persistenta 9-10h", "Flacon spectaculos", "Ideal seara/evenimente"],
             ["Prea intens pentru zi", "Dulce-greu pe vara"],
             {"Familie olfactiva": "Oriental floral", "Note de varf": "Migdale, cafea", "Note de baza": "Tonka, cacao, vanilie", "Concentratie": "Eau de Parfum", "Volum": "80 ml"},
             [mag("notino.ro", "Notino", 419, True), mag("emag.ro", "eMAG", 449), mag("douglas.ro", "Douglas", 439)]),
        prod(5, "Cel mai bun buget", "gray", "Nivea / Bruno Banani Woman", "EDT 60ml", "bbwoman", 99, 8.4,
             {"Persistenta": 8.0, "Sillage": 7.8, "Versatilitate": 8.6, "Ambalaj": 8.0, "Pret/Calitate": 9.3},
             "Fructat-floral accesibil cu performanta peste pret",
             "Pentru un buget mic, Bruno Banani Woman ofera un profil fructat-floral placut si o persistenta surprinzator de buna. Cel mai bun parfum sub 120 lei pentru purtare zilnica.",
             ["Pret foarte accesibil", "Fructat placut", "Bun pentru zi"],
             ["Persistenta 5-6h", "Sillage modest"],
             {"Familie olfactiva": "Fructat floral", "Note de varf": "Rodie, bergamota", "Note de baza": "Musc, lemn de santal", "Concentratie": "Eau de Toilette", "Volum": "60 ml"},
             [mag("notino.ro", "Notino", 99, True), mag("emag.ro", "eMAG", 109)]),
    ],
})

# ── parfumuri-barbati ────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "parfumuri-barbati", "titlu": "Cele mai bune parfumuri de barbati 2026",
    "titlu_scurt": "Parfumuri barbati", "emoji": "🧴", "culoare": "blue", "tag": "RECOMANDAT",
    "descriere": "Top 5 parfumuri de barbati testate pentru persistenta, sillage si versatilitate — de la fresh la lemnos-oriental.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Dior Sauvage", "EDT 100ml", "sauvage", 429, 9.6,
             {"Persistenta": 9.4, "Sillage": 9.5, "Versatilitate": 9.7, "Ambalaj": 9.4, "Pret/Calitate": 9.3},
             "Cel mai versatil parfum masculin — fresh, ambrat, compliment magnet",
             "Sauvage este standardul de aur al parfumurilor masculine moderne: bergamota proaspata peste ambroxan, cu o persistenta excelenta si un sillage care atrage complimente. Functioneaza in orice sezon si ocazie.",
             ["Versatilitate totala", "Compliment magnet", "Persistenta 8-10h", "Potrivit orice sezon"],
             ["Extrem de raspandit", "Ambroxan puternic pentru unii"],
             {"Familie olfactiva": "Aromatic fougere", "Note de varf": "Bergamota de Calabria", "Note de baza": "Ambroxan, cedru", "Concentratie": "Eau de Toilette", "Volum": "100 ml"},
             [mag("notino.ro", "Notino", 429, True), mag("douglas.ro", "Douglas", 459), mag("emag.ro", "eMAG", 469)]),
        prod(2, "Cel mai bun raport pret", "green", "Paco Rabanne Invictus", "EDT 100ml", "invictus", 289, 9.2,
             {"Persistenta": 9.0, "Sillage": 9.3, "Versatilitate": 9.0, "Ambalaj": 9.4, "Pret/Calitate": 9.4},
             "Fresh-acvatic energic, ideal pentru tineri si sala",
             "Invictus este un parfum acvatic-amaruiu, sportiv si energic, perfect pentru barbatul activ. Sillage bun, persistenta solida si un pret excelent il fac un best-buy constant.",
             ["Pret excelent", "Fresh sportiv", "Flacon trofeu iconic", "Bun pentru sala/zi"],
             ["Profil tineresc", "Foarte popular"],
             {"Familie olfactiva": "Acvatic", "Note de varf": "Grapefruit, mandarina", "Note de baza": "Lemn de gaiac, ambergris, paciuli", "Concentratie": "Eau de Toilette", "Volum": "100 ml"},
             [mag("notino.ro", "Notino", 289, True), mag("emag.ro", "eMAG", 309), mag("douglas.ro", "Douglas", 319)]),
        prod(3, "Cel mai elegant", "purple", "Bleu de Chanel", "EDP 100ml", "bleuchanel", 549, 9.4,
             {"Persistenta": 9.3, "Sillage": 9.1, "Versatilitate": 9.5, "Ambalaj": 9.6, "Pret/Calitate": 8.9},
             "Lemnos-aromatic rafinat pentru birou si ocazii formale",
             "Bleu de Chanel EDP este alegerea pentru eleganta sobra: citrice, lemn de santal si tamaie intr-un parfum rafinat, potrivit la birou si evenimente formale. Persistenta foarte buna.",
             ["Eleganta atemporala", "Versatil formal/casual", "Persistenta 9h"],
             ["Pret premium", "Mai sobru, mai putin jucaus"],
             {"Familie olfactiva": "Lemnos aromatic", "Note de varf": "Grapefruit, lamaie, menta", "Note de baza": "Santal, cedru, tamaie", "Concentratie": "Eau de Parfum", "Volum": "100 ml"},
             [mag("notino.ro", "Notino", 549, True), mag("douglas.ro", "Douglas", 579), mag("sephora.ro", "Sephora", 569)]),
        prod(4, "Cel mai bun seara", "blue", "Jean Paul Gaultier Le Male", "EDT 125ml", "lemale", 319, 9.0,
             {"Persistenta": 9.2, "Sillage": 9.0, "Versatilitate": 8.6, "Ambalaj": 9.3, "Pret/Calitate": 9.1},
             "Lavanda-vanilie cald, seducator pentru sezonul rece",
             "Le Male este un clasic oriental-fougere: lavanda, menta si vanilie intr-un sillage cald, dulce, ideal pentru serile reci. Flaconul torso este iconic.",
             ["Cald si seducator", "Persistenta foarte buna", "Flacon iconic", "Excelent toamna/iarna"],
             ["Dulce pentru vara", "Profil divizat"],
             {"Familie olfactiva": "Oriental fougere", "Note de varf": "Menta, lavanda, bergamota", "Note de baza": "Vanilie, tonka, cedru", "Concentratie": "Eau de Toilette", "Volum": "125 ml"},
             [mag("notino.ro", "Notino", 319, True), mag("emag.ro", "eMAG", 339), mag("douglas.ro", "Douglas", 349)]),
        prod(5, "Cel mai bun buget", "gray", "Adidas / STR8 Faded Glory", "EDT 75ml", "str8faded", 79, 8.2,
             {"Persistenta": 7.8, "Sillage": 7.6, "Versatilitate": 8.4, "Ambalaj": 7.8, "Pret/Calitate": 9.2},
             "Aromatic accesibil pentru zi cu zi, sub 100 lei",
             "Pentru bugete mici, STR8 ofera un profil aromatic curat, potrivit pentru zi cu zi. Persistenta modesta dar imbatabil ca pret sub 100 lei.",
             ["Foarte ieftin", "Fresh pentru zi", "Volum generos"],
             ["Persistenta 4-5h", "Sillage redus"],
             {"Familie olfactiva": "Aromatic fougere", "Note de varf": "Bergamota, lavanda", "Note de baza": "Mosc, lemn", "Concentratie": "Eau de Toilette", "Volum": "75 ml"},
             [mag("notino.ro", "Notino", 79, True), mag("emag.ro", "eMAG", 89)]),
    ],
})

# ── pantofi-sport ────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "pantofi-sport", "titlu": "Cei mai buni pantofi sport (sneakers) 2026",
    "titlu_scurt": "Pantofi sport", "emoji": "👟", "culoare": "red", "tag": "POPULAR",
    "descriere": "Top 5 sneakers pentru alergare, sala si lifestyle, evaluati pentru confort, durabilitate si stil.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Nike Air Zoom Pegasus 41", "Pegasus 41", "pegasus41", 549, 9.5,
             {"Confort": 9.6, "Durabilitate": 9.3, "Stil": 9.2, "Amortizare": 9.5, "Pret/Calitate": 9.1},
             "Cel mai versatil sneaker de alergare pentru orice tip de alergator",
             "Pegasus 41 ramane referinta neutra pentru alergare zilnica: amortizare ReactX echilibrata, mesh respirabil si durabilitate excelenta. La fel de bun pe asfalt sau la sala.",
             ["Confort excelent", "Versatil alergare/zi", "Durabilitate ridicata", "Respirabil"],
             ["Design conservator", "Pret peste medie"],
             {"Tip": "Neutru, alergare", "Amortizare": "ReactX + Zoom Air", "Greutate": "~280g", "Drop": "10mm", "Material": "Mesh respirabil"},
             [mag("decathlon.ro", "Decathlon", 549, True), mag("sportisimo.ro", "Sportisimo", 579), mag("emag.ro", "eMAG", 599)]),
        prod(2, "Cel mai bun raport pret", "green", "Adidas Runfalcon 3.0", "Runfalcon 3", "runfalcon3", 219, 9.0,
             {"Confort": 8.8, "Durabilitate": 8.6, "Stil": 8.7, "Amortizare": 8.5, "Pret/Calitate": 9.5},
             "Sneaker accesibil bun pentru alergare usoara si zi cu zi",
             "Runfalcon 3.0 ofera un raport pret/calitate imbatabil: amortizare Cloudfoam confortabila, look curat si pret sub 250 lei. Ideal pentru incepatori si purtare casual.",
             ["Pret excelent", "Confortabil din prima", "Design curat", "Bun pentru zi"],
             ["Durabilitate medie", "Nu pentru alergare intensa"],
             {"Tip": "Neutru, lifestyle/alergare usoara", "Amortizare": "Cloudfoam", "Greutate": "~290g", "Material": "Mesh + sintetic"},
             [mag("decathlon.ro", "Decathlon", 219, True), mag("sportisimo.ro", "Sportisimo", 239), mag("answear.ro", "Answear", 249)]),
        prod(3, "Cel mai bun pentru sala", "blue", "Nike Metcon 9", "Metcon 9", "metcon9", 649, 9.2,
             {"Confort": 9.0, "Durabilitate": 9.5, "Stil": 9.0, "Amortizare": 8.8, "Pret/Calitate": 8.9},
             "Cel mai stabil pantof pentru CrossFit si ridicari",
             "Metcon 9 este standardul pentru antrenamentele functionale: talpa plata stabila pentru ridicari, placa Hyperlift si durabilitate exceptionala pentru burpees si frangii.",
             ["Stabilitate maxima la ridicari", "Foarte durabil", "Excelent CrossFit"],
             ["Rigid pentru alergare", "Pret ridicat"],
             {"Tip": "Antrenament/CrossFit", "Talpa": "Plata, Hyperlift", "Greutate": "~340g", "Material": "Mesh ranforsat"},
             [mag("decathlon.ro", "Decathlon", 649, True), mag("sportisimo.ro", "Sportisimo", 679), mag("emag.ro", "eMAG", 699)]),
        prod(4, "Cel mai confortabil", "purple", "Adidas Ultraboost Light", "Ultraboost Light", "ultraboost", 749, 9.3,
             {"Confort": 9.7, "Durabilitate": 9.0, "Stil": 9.4, "Amortizare": 9.6, "Pret/Calitate": 8.6},
             "Confort premium plush pentru alergare si purtare toata ziua",
             "Ultraboost Light combina spuma Boost cu o constructie usoara Primeknit pentru cel mai placut confort din clasa. Excelent pentru cei care stau mult in picioare.",
             ["Confort plush superior", "Stil premium", "Excelent toata ziua"],
             ["Pret mare", "Greu pentru curse rapide"],
             {"Tip": "Lifestyle/alergare", "Amortizare": "Light Boost", "Greutate": "~300g", "Material": "Primeknit"},
             [mag("answear.ro", "Answear", 749, True), mag("sportisimo.ro", "Sportisimo", 799), mag("emag.ro", "eMAG", 829)]),
        prod(5, "Cel mai bun buget", "gray", "Decathlon Kalenji Run Active", "Run Active", "kalenji", 159, 8.5,
             {"Confort": 8.4, "Durabilitate": 8.2, "Stil": 8.0, "Amortizare": 8.3, "Pret/Calitate": 9.4},
             "Cel mai bun sneaker de alergare sub 180 lei",
             "Run Active de la Kalenji ofera o amortizare decenta si confort bun pentru alergatorii ocazionali, la un pret imbatabil. Punctul de intrare ideal in alergare.",
             ["Foarte ieftin", "Confort bun pentru pret", "Usor"],
             ["Durabilitate limitata", "Design simplu"],
             {"Tip": "Alergare ocazionala", "Amortizare": "EVA", "Greutate": "~270g", "Material": "Mesh"},
             [mag("decathlon.ro", "Decathlon", 159, True)]),
    ],
})

# ── genti-dama ───────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "genti-dama", "titlu": "Cele mai bune genti de dama 2026",
    "titlu_scurt": "Genti dama", "emoji": "👜", "culoare": "pink", "tag": "TRENDING",
    "descriere": "Top 5 genti de dama pentru orice ocazie — de la tote office la crossbody elegant, evaluate pentru calitate, capacitate si stil.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Geanta Tote piele ecologica", "Office Tote", "tote-office", 249, 9.3,
             {"Calitate": 9.2, "Capacitate": 9.5, "Stil": 9.3, "Functionalitate": 9.4, "Pret/Calitate": 9.2},
             "Cea mai practica geanta tote pentru birou si laptop",
             "O tote spatioasa din piele ecologica, cu compartiment pentru laptop de 14 inch si finisaje premium. Cea mai buna alegere pentru femeia activa care vrea eleganta si functionalitate.",
             ["Incape laptop 14 inch", "Piele ecologica de calitate", "Eleganta versatila", "Pret corect"],
             ["Fara inchidere cu fermoar la unele modele", "Culori limitate"],
             {"Material": "Piele ecologica (PU premium)", "Dimensiuni": "35x28x12 cm", "Compartimente": "3 + buzunar laptop", "Inchidere": "Magnetica/fermoar"},
             [mag("answear.ro", "Answear", 249, True), mag("epantofi.ro", "ePantofi", 279), mag("emag.ro", "eMAG", 269)]),
        prod(2, "Cel mai bun raport pret", "green", "Geanta Crossbody mini", "Crossbody Mini", "crossbody", 129, 9.0,
             {"Calitate": 8.8, "Capacitate": 8.2, "Stil": 9.4, "Functionalitate": 9.0, "Pret/Calitate": 9.5},
             "Crossbody compact, perfect pentru iesiri si oras",
             "O geanta crossbody mini, usoara si stilata, perfecta pentru esential: telefon, portofel, chei. Curea reglabila si design modern la un pret excelent.",
             ["Foarte stilata", "Usoara si practica", "Pret accesibil", "Curea reglabila"],
             ["Capacitate mica", "Nu pentru laptop"],
             {"Material": "PU / saffiano", "Dimensiuni": "20x14x7 cm", "Curea": "Reglabila, detasabila", "Inchidere": "Fermoar"},
             [mag("answear.ro", "Answear", 129, True), mag("epantofi.ro", "ePantofi", 149)]),
        prod(3, "Cea mai eleganta", "purple", "Geanta umar piele naturala", "Shoulder Lux", "shoulder-lux", 449, 9.2,
             {"Calitate": 9.6, "Capacitate": 8.8, "Stil": 9.5, "Functionalitate": 9.0, "Pret/Calitate": 8.7},
             "Piele naturala premium pentru un look rafinat",
             "Geanta de umar din piele naturala, cu finisaje de lux si o silueta atemporala. Investitia ideala pentru o piesa care rezista ani de zile si ridica orice tinuta.",
             ["Piele naturala durabila", "Look premium atemporal", "Finisaje de calitate"],
             ["Pret ridicat", "Necesita intretinere piele"],
             {"Material": "Piele naturala", "Dimensiuni": "30x22x10 cm", "Compartimente": "2 + buzunar interior", "Inchidere": "Fermoar"},
             [mag("epantofi.ro", "ePantofi", 449, True), mag("answear.ro", "Answear", 479), mag("emag.ro", "eMAG", 499)]),
        prod(4, "Cea mai incapatoare", "blue", "Geanta Shopper XL", "Shopper XL", "shopper-xl", 199, 8.9,
             {"Calitate": 8.6, "Capacitate": 9.7, "Stil": 8.6, "Functionalitate": 9.3, "Pret/Calitate": 9.1},
             "Shopper mare pentru cumparaturi, plaja sau weekend",
             "O shopper XL extrem de incapatoare, ideala pentru cumparaturi, plaja sau o escapada de weekend. Rezistenta si usor de purtat pe umar.",
             ["Capacitate uriasa", "Rezistenta", "Multifunctionala"],
             ["Mai putin eleganta", "Lipsa structura"],
             {"Material": "Canvas / PU", "Dimensiuni": "42x35x15 cm", "Compartimente": "1 mare + buzunar", "Inchidere": "Magnetica"},
             [mag("answear.ro", "Answear", 199, True), mag("emag.ro", "eMAG", 219)]),
        prod(5, "Cea mai buna buget", "gray", "Geanta plic clutch", "Clutch Evening", "clutch", 89, 8.4,
             {"Calitate": 8.2, "Capacitate": 7.6, "Stil": 9.2, "Functionalitate": 8.0, "Pret/Calitate": 9.4},
             "Plic elegant pentru evenimente, sub 100 lei",
             "Un clutch elegant pentru seri si evenimente, cu detalii metalice si lant detasabil. Cea mai accesibila modalitate de a completa o tinuta de ocazie.",
             ["Pret mic", "Elegant pentru evenimente", "Lant detasabil"],
             ["Capacitate foarte mica", "Doar pentru ocazii"],
             {"Material": "Satin / PU", "Dimensiuni": "24x13x4 cm", "Lant": "Detasabil", "Inchidere": "Clic-clac"},
             [mag("answear.ro", "Answear", 89, True), mag("epantofi.ro", "ePantofi", 99)]),
    ],
})

# ── bijuterii-argint ─────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "bijuterii-argint", "titlu": "Cele mai bune bijuterii din argint 2026",
    "titlu_scurt": "Bijuterii argint", "emoji": "💍", "culoare": "blue", "tag": "CADOU IDEAL",
    "descriere": "Top 5 bijuterii din argint 925 pentru cadou — coliere, cercei, inele si bratari evaluate pentru calitate si raport pret/valoare.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Colier argint 925 cu pandantiv", "Inima Zirconiu", "colier-925", 149, 9.3,
             {"Calitate": 9.4, "Design": 9.2, "Durabilitate": 9.0, "Ambalaj cadou": 9.5, "Pret/Calitate": 9.3},
             "Cel mai popular cadou — colier argint cu pandantiv zirconiu",
             "Un colier din argint 925 cu pandantiv in forma de inima si zirconiu cubic, livrat in cutie cadou. Cea mai sigura alegere pentru aniversari, Valentine's si ocazii speciale.",
             ["Argint 925 certificat", "Cutie cadou inclusa", "Design atemporal", "Pret excelent pentru cadou"],
             ["Lant subtire la unele modele", "Zirconiu, nu diamant"],
             {"Material": "Argint 925", "Piatra": "Zirconiu cubic", "Lungime lant": "40-45 cm reglabil", "Ambalaj": "Cutie cadou"},
             [mag("emag.ro", "eMAG", 149, True), mag("answear.ro", "Answear", 169)]),
        prod(2, "Cel mai bun raport pret", "green", "Cercei argint 925 tortite", "Hoops Clasic", "cercei-hoops", 79, 9.0,
             {"Calitate": 8.9, "Design": 9.0, "Durabilitate": 8.8, "Ambalaj cadou": 8.6, "Pret/Calitate": 9.5},
             "Cercei hoops versatili pentru purtare zilnica",
             "Cercei rotunzi (hoops) din argint 925, usori si versatili, potriviti pentru orice tinuta. Cel mai bun raport pret/calitate pentru purtare de zi cu zi.",
             ["Foarte versatili", "Usori si comozi", "Pret accesibil", "Argint 925"],
             ["Design simplu", "Fara piatra"],
             {"Material": "Argint 925", "Diametru": "20 mm", "Inchidere": "Click", "Greutate": "Usori"},
             [mag("emag.ro", "eMAG", 79, True), mag("answear.ro", "Answear", 89)]),
        prod(3, "Cel mai elegant", "purple", "Set argint colier + cercei", "Set Bridal", "set-bridal", 229, 9.2,
             {"Calitate": 9.3, "Design": 9.4, "Durabilitate": 9.0, "Ambalaj cadou": 9.4, "Pret/Calitate": 8.9},
             "Set complet colier si cercei pentru ocazii speciale",
             "Un set coordonat din argint 925 cu colier si cercei asortati, perfect pentru nunti, botezuri si evenimente. Livrat in cutie premium, ideal pentru un cadou impresionant.",
             ["Set coordonat complet", "Aspect premium", "Cutie cadou premium", "Ideal pentru evenimente"],
             ["Pret mai mare", "Mai festiv decat casual"],
             {"Material": "Argint 925", "Continut": "Colier + 1 pereche cercei", "Pietre": "Zirconiu", "Ambalaj": "Cutie premium"},
             [mag("emag.ro", "eMAG", 229, True), mag("answear.ro", "Answear", 259)]),
        prod(4, "Cel mai versatil", "blue", "Bratara argint cu charm", "Charm Bracelet", "bratara-charm", 119, 8.9,
             {"Calitate": 8.8, "Design": 9.1, "Durabilitate": 8.7, "Ambalaj cadou": 9.0, "Pret/Calitate": 9.2},
             "Bratara cu charm-uri, personalizabila in timp",
             "O bratara din argint 925 compatibila cu charm-uri, care poate fi personalizata cu talismane adaugate la fiecare ocazie. Un cadou care creste in timp.",
             ["Personalizabila cu charms", "Cadou care creste in timp", "Argint 925"],
             ["Charm-urile se cumpara separat", "Inchidere fina"],
             {"Material": "Argint 925", "Tip": "Snake bracelet compatibil charms", "Lungime": "18-20 cm", "Inchidere": "Clip siguranta"},
             [mag("emag.ro", "eMAG", 119, True), mag("answear.ro", "Answear", 139)]),
        prod(5, "Cel mai bun buget", "gray", "Inel argint 925 reglabil", "Inel Minimalist", "inel-925", 49, 8.5,
             {"Calitate": 8.4, "Design": 8.6, "Durabilitate": 8.3, "Ambalaj cadou": 8.2, "Pret/Calitate": 9.4},
             "Inel minimalist reglabil sub 60 lei",
             "Un inel minimalist din argint 925, reglabil pentru a se potrivi oricarui deget. Cea mai accesibila bijuterie din argint, perfecta ca mic cadou sau accesoriu zilnic.",
             ["Foarte ieftin", "Reglabil universal", "Minimalist modern"],
             ["Subtire", "Fara piatra"],
             {"Material": "Argint 925", "Tip": "Reglabil", "Marime": "Universala", "Stil": "Minimalist"},
             [mag("emag.ro", "eMAG", 49, True)]),
    ],
})

# ── jucarii-copii ────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "jucarii-copii", "titlu": "Cele mai bune jucarii pentru copii 2026",
    "titlu_scurt": "Jucarii copii", "emoji": "🧸", "culoare": "yellow", "tag": "CADOU IDEAL",
    "descriere": "Top 5 jucarii educative si distractive pe categorii de varsta, evaluate pentru valoare educativa, calitate si distractie.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Set LEGO Classic constructie", "Classic 11717", "lego-classic", 179, 9.4,
             {"Valoare educativa": 9.6, "Calitate": 9.5, "Distractie": 9.4, "Durabilitate": 9.5, "Pret/Calitate": 9.2},
             "Cea mai buna jucarie pentru creativitate, 4-99 ani",
             "Un set LEGO Classic cu sute de piese variate stimuleaza creativitatea si motricitatea fina. Cadoul ideal care se joaca ani de zile si creste odata cu copilul.",
             ["Stimuleaza creativitatea", "Durabilitate excelenta", "Potrivit varsta larga", "Compatibil cu alte seturi"],
             ["Piese mici (sub 3 ani nu)", "Necesita spatiu depozitare"],
             {"Varsta": "4+ ani", "Piese": "~500", "Material": "Plastic ABS premium", "Tip": "Constructie creativa"},
             [mag("noriel.ro", "Noriel", 179, True), mag("emag.ro", "eMAG", 199), mag("elefant.ro", "Elefant", 189)]),
        prod(2, "Cel mai bun raport pret", "green", "Puzzle educativ lemn", "Puzzle Animale", "puzzle-lemn", 59, 9.0,
             {"Valoare educativa": 9.3, "Calitate": 8.9, "Distractie": 8.8, "Durabilitate": 9.1, "Pret/Calitate": 9.5},
             "Puzzle din lemn pentru dezvoltare cognitiva 2-5 ani",
             "Un puzzle din lemn cu animale, ideal pentru dezvoltarea cognitiva si a coordonarii la copiii mici. Materiale sigure, sustenabile si pret excelent.",
             ["Lemn sigur sustenabil", "Dezvolta logica", "Pret mic", "Durabil"],
             ["Numar limitat de piese", "Pentru varsta mica"],
             {"Varsta": "2-5 ani", "Material": "Lemn natural", "Piese": "9-16", "Tip": "Puzzle educativ"},
             [mag("noriel.ro", "Noriel", 59, True), mag("elefant.ro", "Elefant", 69)]),
        prod(3, "Cel mai distractiv", "purple", "Masina telecomanda off-road", "RC Buggy 4WD", "rc-buggy", 199, 9.1,
             {"Valoare educativa": 8.0, "Calitate": 9.0, "Distractie": 9.7, "Durabilitate": 8.8, "Pret/Calitate": 9.0},
             "Masina RC 4WD pentru distractie maxima, 6+ ani",
             "O masina cu telecomanda 4WD, rezistenta la teren accidentat, cu baterie reincarcabila. Cadoul preferat al copiilor activi care vor distractie in aer liber.",
             ["Distractie garantata", "4WD off-road", "Baterie reincarcabila", "Rezistenta la socuri"],
             ["Autonomie ~20 min", "Valoare educativa redusa"],
             {"Varsta": "6+ ani", "Tractiune": "4WD", "Autonomie": "~20 min", "Raza": "~30m", "Baterie": "Reincarcabila"},
             [mag("noriel.ro", "Noriel", 199, True), mag("emag.ro", "eMAG", 229)]),
        prod(4, "Cel mai educativ", "blue", "Microscop / kit stiinta copii", "STEM Lab", "stem-lab", 149, 9.2,
             {"Valoare educativa": 9.7, "Calitate": 9.0, "Distractie": 9.0, "Durabilitate": 8.8, "Pret/Calitate": 9.1},
             "Kit STEM care transforma invatarea in joaca, 8+ ani",
             "Un kit de stiinta cu experimente sigure si microscop, care stimuleaza curiozitatea si gandirea logica. Ideal pentru copiii pasionati de descoperire.",
             ["Invatare prin joaca", "Multe experimente incluse", "Stimuleaza curiozitatea STEM"],
             ["Necesita supraveghere", "Pentru copii mai mari"],
             {"Varsta": "8+ ani", "Continut": "Microscop + 30 experimente", "Domeniu": "STEM/stiinta", "Material": "Plastic + sticla"},
             [mag("noriel.ro", "Noriel", 149, True), mag("elefant.ro", "Elefant", 169), mag("emag.ro", "eMAG", 159)]),
        prod(5, "Cel mai bun buget", "gray", "Set plus / jucarie senzoriala", "Plus Senzorial", "plus-senzorial", 39, 8.6,
             {"Valoare educativa": 8.4, "Calitate": 8.5, "Distractie": 8.8, "Durabilitate": 8.6, "Pret/Calitate": 9.3},
             "Jucarie de plus moale, sigura pentru bebelusi",
             "O jucarie de plus moale si sigura, perfecta pentru bebelusi si copii mici. Materiale hipoalergenice, lavabila, ideala ca prim cadou la pret mic.",
             ["Sigura pentru bebelusi", "Materiale moi lavabile", "Pret foarte mic"],
             ["Simpla", "Fara componenta educativa avansata"],
             {"Varsta": "0+ ani", "Material": "Plus hipoalergenic", "Intretinere": "Lavabila", "Tip": "Senzorial/confort"},
             [mag("noriel.ro", "Noriel", 39, True), mag("emag.ro", "eMAG", 45)]),
    ],
})

# ── suplimente-fitness ───────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "suplimente-fitness", "titlu": "Cele mai bune suplimente fitness 2026",
    "titlu_scurt": "Suplimente fitness", "emoji": "💪", "culoare": "red", "tag": "RECOMANDAT",
    "descriere": "Top 5 suplimente esentiale pentru masa musculara si recuperare, evaluate pentru eficienta, ingrediente si raport pret/portie.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Proteina Whey izolat", "Whey Isolate 900g", "whey-iso", 169, 9.4,
             {"Eficienta": 9.5, "Ingrediente": 9.3, "Gust": 9.0, "Solubilitate": 9.2, "Pret/Portie": 9.2},
             "Cea mai buna proteina pentru crestere si recuperare musculara",
             "O proteina whey izolat cu peste 80% proteina per portie, absorbtie rapida si continut scazut de lactoza. Esentiala pentru oricine vrea masa musculara si recuperare optima.",
             ["80%+ proteina per portie", "Absorbtie rapida", "Lactoza redusa", "Se dizolva usor"],
             ["Pret mai mare ca whey concentrat", "Gust variabil intre arome"],
             {"Tip": "Whey izolat", "Proteina/portie": "~27g", "Portii": "30", "Aroma": "Ciocolata/vanilie"},
             [mag("secom.ro", "Secom", 169, True), mag("farmacia-tei.ro", "Farmacia Tei", 189), mag("emag.ro", "eMAG", 179)]),
        prod(2, "Cel mai bun raport pret", "green", "Creatina monohidrat", "Creatine 500g", "creatina", 89, 9.3,
             {"Eficienta": 9.6, "Ingrediente": 9.4, "Gust": 8.5, "Solubilitate": 8.8, "Pret/Portie": 9.6},
             "Suplimentul cu cele mai multe dovezi stiintifice, pret mic",
             "Creatina monohidrat este cel mai studiat si eficient supliment pentru forta si masa musculara. 500g acopera luni intregi la un pret excelent — un must-have.",
             ["Eficienta dovedita stiintific", "Foarte ieftin pe portie", "Creste forta si masa"],
             ["Retentie usoara de apa initial", "Fara aroma"],
             {"Tip": "Monohidrat micronizat", "Doza zilnica": "5g", "Portii": "100", "Aroma": "Neutra"},
             [mag("secom.ro", "Secom", 89, True), mag("farmacia-tei.ro", "Farmacia Tei", 99)]),
        prod(3, "Cea mai buna recuperare", "purple", "BCAA / EAA pudra", "EAA 400g", "eaa", 129, 9.0,
             {"Eficienta": 9.0, "Ingrediente": 9.2, "Gust": 9.3, "Solubilitate": 9.0, "Pret/Portie": 8.7},
             "Aminoacizi esentiali pentru recuperare si anti-catabolism",
             "Un complex de aminoacizi esentiali (EAA) care sustine recuperarea si reduce catabolismul muscular in timpul antrenamentelor lungi sau in deficit caloric.",
             ["Sustine recuperarea", "Gust placut intra-workout", "Util in deficit caloric"],
             ["Mai putin esential daca aportul de proteina e suficient", "Pret per portie mediu"],
             {"Tip": "EAA complet", "Aminoacizi": "Toti 9 esentiali", "Portii": "40", "Aroma": "Fructe"},
             [mag("secom.ro", "Secom", 129, True), mag("emag.ro", "eMAG", 145)]),
        prod(4, "Cel mai bun pre-workout", "blue", "Pre-workout cu cofeina", "Pre-WO 300g", "preworkout", 119, 8.9,
             {"Eficienta": 9.1, "Ingrediente": 8.8, "Gust": 9.2, "Solubilitate": 9.0, "Pret/Portie": 8.6},
             "Energie si focus pentru antrenamente intense",
             "Un pre-workout cu cofeina, beta-alanina si citrulina pentru energie, focus si pompa musculara. Ideal pentru sesiunile grele cand ai nevoie de un boost.",
             ["Energie si focus crescut", "Pompa musculara buna", "Gust bun"],
             ["Cofeina poate afecta somnul seara", "Furnicaturi de la beta-alanina"],
             {"Tip": "Pre-workout stimulant", "Cofeina/portie": "~200mg", "Portii": "30", "Aroma": "Fructe"},
             [mag("secom.ro", "Secom", 119, True), mag("emag.ro", "eMAG", 135)]),
        prod(5, "Cel mai bun buget", "gray", "Vitamina D3 + Omega 3", "D3+Omega", "d3-omega", 49, 8.7,
             {"Eficienta": 8.8, "Ingrediente": 9.0, "Gust": 8.5, "Solubilitate": 8.5, "Pret/Portie": 9.3},
             "Baza de sanatate accesibila pentru orice sportiv",
             "Combinatia D3 + Omega 3 sustine sanatatea articulatiilor, imunitatea si recuperarea. Un supliment de baza, ieftin, recomandat oricarui sportiv, mai ales iarna.",
             ["Sustine articulatiile si imunitatea", "Pret foarte mic", "Util tot anul"],
             ["Efect indirect asupra performantei", "Necesita consum constant"],
             {"Tip": "Vitamina D3 + ulei de peste", "D3/portie": "2000 UI", "Portii": "60", "Forma": "Capsule"},
             [mag("secom.ro", "Secom", 49, True), mag("farmacia-tei.ro", "Farmacia Tei", 55)]),
    ],
})

# ── scaune-birou ─────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "scaune-birou", "titlu": "Cele mai bune scaune de birou ergonomice 2026",
    "titlu_scurt": "Scaune birou", "emoji": "🪑", "culoare": "blue", "tag": "POPULAR",
    "descriere": "Top 5 scaune de birou ergonomice pentru lucru de acasa, evaluate pentru confort, suport lombar si durabilitate.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Scaun ergonomic mesh premium", "ErgoMesh Pro", "ergomesh", 1290, 9.4,
             {"Confort": 9.5, "Suport lombar": 9.6, "Reglaje": 9.4, "Durabilitate": 9.3, "Pret/Calitate": 9.0},
             "Cel mai bun scaun ergonomic pentru lucru 8h+ pe zi",
             "Un scaun ergonomic cu spatar din mesh respirabil, suport lombar reglabil si cotiere 4D. Cea mai buna alegere pentru cei care lucreaza multe ore la birou, cu sustinere reala a spatelui.",
             ["Suport lombar reglabil excelent", "Mesh respirabil", "Cotiere 4D", "Constructie solida"],
             ["Pret ridicat", "Asamblare necesara"],
             {"Tip spatar": "Mesh respirabil", "Lombar": "Reglabil pe inaltime", "Cotiere": "4D", "Greutate maxima": "120 kg", "Inclinare": "Pana la 135°"},
             [mag("emag.ro", "eMAG", 1290, True), mag("altex.ro", "Altex", 1390), mag("vidaxl.ro", "vidaXL", 1350)]),
        prod(2, "Cel mai bun raport pret", "green", "Scaun birou mesh mid-back", "ComfortMesh", "comfortmesh", 549, 9.0,
             {"Confort": 8.9, "Suport lombar": 8.8, "Reglaje": 8.6, "Durabilitate": 8.8, "Pret/Calitate": 9.5},
             "Ergonomie decenta la pret accesibil pentru home-office",
             "Un scaun mesh mid-back cu suport lombar de baza si reglaje esentiale, ideal pentru home-office la un pret accesibil. Cel mai bun raport pret/ergonomie sub 600 lei.",
             ["Pret excelent", "Mesh respirabil", "Reglaje esentiale", "Asamblare usoara"],
             ["Lombar mai putin reglabil", "Cotiere simple"],
             {"Tip spatar": "Mesh mid-back", "Lombar": "Fix integrat", "Cotiere": "Fixe/2D", "Greutate maxima": "110 kg"},
             [mag("emag.ro", "eMAG", 549, True), mag("altex.ro", "Altex", 599), mag("vidaxl.ro", "vidaXL", 569)]),
        prod(3, "Cel mai confortabil", "purple", "Scaun executiv piele ecologica", "Executive Lux", "executive", 899, 9.1,
             {"Confort": 9.4, "Suport lombar": 9.0, "Reglaje": 8.8, "Durabilitate": 9.0, "Pret/Calitate": 8.8},
             "Confort plush si aspect premium pentru birou clasic",
             "Un scaun executiv din piele ecologica, cu padding generos si tetiera, pentru cei care prefera confortul plush si un aspect elegant clasic in detrimentul mesh-ului sportiv.",
             ["Confort plush superior", "Aspect premium", "Tetiera inclusa"],
             ["Mai putin respirabil decat mesh", "Voluminos"],
             {"Tip spatar": "Piele ecologica + padding", "Tetiera": "Da", "Cotiere": "Reglabile pe inaltime", "Greutate maxima": "130 kg"},
             [mag("emag.ro", "eMAG", 899, True), mag("vidaxl.ro", "vidaXL", 949)]),
        prod(4, "Cel mai bun gaming/birou", "blue", "Scaun hibrid gaming-office", "HybridChair", "hybrid", 749, 8.9,
             {"Confort": 9.0, "Suport lombar": 8.9, "Reglaje": 9.0, "Durabilitate": 8.7, "Pret/Calitate": 9.1},
             "Hibrid gaming-office cu perne lombare si cervicale",
             "Un scaun hibrid care imbina estetica gaming cu ergonomia de birou: perne lombare si cervicale, inclinare ampla si cotiere reglabile. Bun pentru lucru si relaxare.",
             ["Versatil munca/gaming", "Perne lombar+cervical", "Inclinare ampla 155°"],
             ["Estetica gaming nu place tuturor", "Padding se aseaza in timp"],
             {"Tip spatar": "Imitatie piele + perne", "Inclinare": "Pana la 155°", "Cotiere": "Reglabile", "Greutate maxima": "120 kg"},
             [mag("emag.ro", "eMAG", 749, True), mag("altex.ro", "Altex", 799), mag("pcgarage.ro", "PC Garage", 779)]),
        prod(5, "Cel mai bun buget", "gray", "Scaun birou simplu reglabil", "BasicTask", "basictask", 299, 8.3,
             {"Confort": 8.2, "Suport lombar": 7.9, "Reglaje": 8.0, "Durabilitate": 8.2, "Pret/Calitate": 9.2},
             "Scaun functional pentru utilizare ocazionala, sub 300 lei",
             "Un scaun de birou simplu, cu reglaj de inaltime si inclinare de baza, potrivit pentru utilizare ocazionala sau bugete stranse. Functional si accesibil.",
             ["Pret foarte mic", "Reglaj inaltime", "Compact"],
             ["Suport lombar minimal", "Nu pentru 8h zilnic"],
             {"Tip spatar": "Mesh/textil mic", "Lombar": "Minimal", "Cotiere": "Fixe", "Greutate maxima": "100 kg"},
             [mag("emag.ro", "eMAG", 299, True), mag("vidaxl.ro", "vidaXL", 319)]),
    ],
})

# ── tablete ──────────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "tablete", "titlu": "Cele mai bune tablete 2026",
    "titlu_scurt": "Tablete", "emoji": "📲", "culoare": "blue", "tag": "POPULAR",
    "descriere": "Top 5 tablete pentru divertisment, productivitate si copii, evaluate pentru performanta, ecran si autonomie.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Apple iPad (A16)", "iPad 11", "ipad-a16", 2199, 9.5,
             {"Performanta": 9.5, "Ecran": 9.4, "Autonomie": 9.3, "Software": 9.7, "Pret/Calitate": 9.1},
             "Cea mai buna tableta pentru majoritatea utilizatorilor",
             "iPad-ul de baza ramane cea mai echilibrata tableta: chip rapid A16, ecran Liquid Retina excelent si suport software indelungat. Perfect pentru divertisment, scoala si productivitate usoara.",
             ["Performanta excelenta", "Suport software 6+ ani", "Ecosistem accesorii bogat", "Autonomie buna"],
             ["Stylus si tastatura separate", "Stocare de baza 128GB"],
             {"Ecran": "11 inch Liquid Retina", "Chip": "A16", "Stocare": "128/256 GB", "Autonomie": "~10h", "Conectivitate": "Wi-Fi / 5G optional"},
             [mag("emag.ro", "eMAG", 2199, True), mag("altex.ro", "Altex", 2299), mag("evomag.ro", "evoMAG", 2249)]),
        prod(2, "Cel mai bun raport pret", "green", "Xiaomi Redmi Pad SE", "Redmi Pad SE", "redmi-pad", 799, 9.1,
             {"Performanta": 8.8, "Ecran": 9.0, "Autonomie": 9.3, "Software": 8.7, "Pret/Calitate": 9.6},
             "Cea mai buna tableta Android sub 900 lei",
             "Redmi Pad SE ofera un ecran mare de 11 inch 90Hz, autonomie excelenta si performanta decenta pentru media si navigare, la un pret imbatabil. Ideal pentru consum de continut.",
             ["Pret excelent", "Ecran 90Hz mare", "Autonomie foarte buna", "Difuzoare bune"],
             ["Performanta medie la jocuri grele", "Fara 5G"],
             {"Ecran": "11 inch 90Hz", "Chip": "Snapdragon 680", "Stocare": "128/256 GB", "Autonomie": "~12h", "Conectivitate": "Wi-Fi"},
             [mag("emag.ro", "eMAG", 799, True), mag("altex.ro", "Altex", 849), mag("quickmobile.ro", "QuickMobile", 829)]),
        prod(3, "Cea mai buna premium", "purple", "Samsung Galaxy Tab S9 FE", "Tab S9 FE", "tab-s9fe", 1999, 9.3,
             {"Performanta": 9.2, "Ecran": 9.4, "Autonomie": 9.2, "Software": 9.1, "Pret/Calitate": 8.9},
             "Premium Android cu S Pen inclus si rezistenta la apa",
             "Galaxy Tab S9 FE vine cu S Pen inclus, ecran de 10.9 inch si rezistenta IP68, fiind alegerea premium Android pentru notite, desen si productivitate.",
             ["S Pen inclus", "Rezistenta la apa IP68", "Ecran foarte bun", "DeX pentru productivitate"],
             ["Pret ridicat", "Incarcator separat"],
             {"Ecran": "10.9 inch 90Hz", "Chip": "Exynos 1380", "Stocare": "128/256 GB", "S Pen": "Inclus", "Rezistenta": "IP68"},
             [mag("emag.ro", "eMAG", 1999, True), mag("altex.ro", "Altex", 2099), mag("evomag.ro", "evoMAG", 2049)]),
        prod(4, "Cea mai buna pentru copii", "blue", "Lenovo Tab M11 Kids", "Tab M11", "tab-m11", 999, 8.9,
             {"Performanta": 8.6, "Ecran": 8.9, "Autonomie": 9.2, "Software": 8.8, "Pret/Calitate": 9.2},
             "Tableta robusta cu control parental pentru copii",
             "Tab M11 cu husa de protectie si control parental Google Kids Space este ideala pentru cei mici: rezistenta, autonomie buna si continut sigur, supravegheat.",
             ["Husa protectie inclusa", "Control parental robust", "Autonomie buna", "Stylus inclus la unele variante"],
             ["Performanta modesta", "Ecran LCD obisnuit"],
             {"Ecran": "11 inch 90Hz", "Chip": "MediaTek G88", "Stocare": "128 GB", "Extra": "Husa + control parental", "Autonomie": "~11h"},
             [mag("emag.ro", "eMAG", 999, True), mag("altex.ro", "Altex", 1049)]),
        prod(5, "Cea mai buna buget", "gray", "Lenovo Tab M9", "Tab M9", "tab-m9", 549, 8.4,
             {"Performanta": 8.0, "Ecran": 8.3, "Autonomie": 8.8, "Software": 8.4, "Pret/Calitate": 9.3},
             "Tableta de baza pentru media si navigare, sub 600 lei",
             "Tab M9 acopera nevoile de baza — YouTube, navigare, citit — la un pret mic. Cea mai accesibila tableta de incredere pentru utilizare casual sau a doua tableta in casa.",
             ["Pret foarte mic", "Compacta si usoara", "Autonomie decenta"],
             ["Performanta limitata", "Ecran HD obisnuit"],
             {"Ecran": "9 inch HD", "Chip": "MediaTek G80", "Stocare": "32/64 GB", "Autonomie": "~10h", "Conectivitate": "Wi-Fi/LTE"},
             [mag("emag.ro", "eMAG", 549, True), mag("altex.ro", "Altex", 579)]),
    ],
})

# ── casti-gaming ─────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "casti-gaming", "titlu": "Cele mai bune casti gaming 2026",
    "titlu_scurt": "Casti gaming", "emoji": "🎧", "culoare": "purple", "tag": "RECOMANDAT",
    "descriere": "Top 5 casti gaming wireless si cu fir, evaluate pentru sunet, microfon, confort si autonomie.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "SteelSeries Arctis Nova 7", "Nova 7", "nova7", 749, 9.4,
             {"Sunet": 9.4, "Microfon": 9.3, "Confort": 9.5, "Autonomie": 9.2, "Pret/Calitate": 9.1},
             "Cele mai echilibrate casti gaming wireless",
             "Arctis Nova 7 ofera sunet excelent, microfon clar retractabil si un confort de top pentru sesiuni lungi. Conectivitate dual wireless (2.4GHz + Bluetooth) o face extrem de versatila.",
             ["Confort exceptional", "Microfon clar", "Dual wireless 2.4G+BT", "Autonomie ~38h"],
             ["Pret peste medie", "Fara ANC"],
             {"Conectivitate": "2.4GHz + Bluetooth", "Autonomie": "~38h", "Driver": "40mm", "Microfon": "Retractabil ClearCast", "Compatibilitate": "PC/PS/Switch"},
             [mag("emag.ro", "eMAG", 749, True), mag("pcgarage.ro", "PC Garage", 779), mag("altex.ro", "Altex", 799)]),
        prod(2, "Cel mai bun raport pret", "green", "HyperX Cloud Stinger 2", "Stinger 2", "stinger2", 219, 9.1,
             {"Sunet": 8.9, "Microfon": 8.8, "Confort": 9.0, "Autonomie": 8.0, "Pret/Calitate": 9.6},
             "Cele mai bune casti gaming cu fir sub 250 lei",
             "Cloud Stinger 2 ofera sunet bun, microfon decent si confort surprinzator la un pret mic. Cea mai sigura alegere cu fir pentru bugete reduse.",
             ["Pret excelent", "Confortabile usoare", "Microfon swivel-to-mute", "Sunet bun"],
             ["Cu fir doar", "Constructie plastic"],
             {"Conectivitate": "Cu fir 3.5mm", "Driver": "50mm", "Microfon": "Flip-to-mute", "Greutate": "~275g", "Compatibilitate": "PC/console"},
             [mag("emag.ro", "eMAG", 219, True), mag("pcgarage.ro", "PC Garage", 239)]),
        prod(3, "Cele mai premium", "purple", "Razer BlackShark V2 Pro", "BlackShark V2 Pro", "blackshark", 999, 9.3,
             {"Sunet": 9.5, "Microfon": 9.4, "Confort": 9.3, "Autonomie": 9.0, "Pret/Calitate": 8.8},
             "Premium e-sport cu sunet detaliat si microfon de top",
             "BlackShark V2 Pro este alegerea pentru jucatorii competitivi: sunet detaliat cu directionalitate excelenta, microfon detasabil de calitate si izolare buna a zgomotului.",
             ["Sunet competitiv detaliat", "Microfon detasabil excelent", "Izolare buna", "Wireless lag redus"],
             ["Pret premium", "Estetica e-sport sobra"],
             {"Conectivitate": "2.4GHz wireless", "Autonomie": "~70h", "Driver": "50mm TriForce", "Microfon": "HyperClear detasabil", "Compatibilitate": "PC/PS"},
             [mag("emag.ro", "eMAG", 999, True), mag("pcgarage.ro", "PC Garage", 1049), mag("evomag.ro", "evoMAG", 1029)]),
        prod(4, "Cel mai bun confort", "blue", "Logitech G535 Wireless", "G535", "g535", 449, 9.0,
             {"Sunet": 8.9, "Microfon": 8.7, "Confort": 9.4, "Autonomie": 8.8, "Pret/Calitate": 9.2},
             "Wireless usor si confortabil pentru sesiuni lungi",
             "G535 este una dintre cele mai usoare casti wireless, foarte confortabila pentru ore intregi de joc. Sunet bun si microfon cu flip-to-mute, la un pret rezonabil.",
             ["Foarte usoare 236g", "Wireless accesibil", "Microfon flip-to-mute", "Confort prelungit"],
             ["Bass mai modest", "Autonomie medie ~33h"],
             {"Conectivitate": "Lightspeed 2.4GHz", "Autonomie": "~33h", "Driver": "40mm", "Greutate": "236g", "Compatibilitate": "PC/PS"},
             [mag("emag.ro", "eMAG", 449, True), mag("pcgarage.ro", "PC Garage", 479), mag("altex.ro", "Altex", 469)]),
        prod(5, "Cele mai bune buget", "gray", "Trust GXT 415 / Redragon", "GXT Zirox", "gxt-zirox", 99, 8.3,
             {"Sunet": 8.0, "Microfon": 7.9, "Confort": 8.4, "Autonomie": 8.0, "Pret/Calitate": 9.3},
             "Casti gaming functionale sub 120 lei",
             "Pentru un buget minim, aceste casti cu fir ofera sunet decent si microfon functional pentru jocuri casual si comunicare. Cea mai accesibila intrare in gaming audio.",
             ["Pret foarte mic", "Microfon functional", "Confort decent"],
             ["Sunet de baza", "Constructie simpla"],
             {"Conectivitate": "Cu fir 3.5mm/USB", "Driver": "50mm", "Microfon": "Flexibil", "Compatibilitate": "PC/console"},
             [mag("emag.ro", "eMAG", 99, True), mag("pcgarage.ro", "PC Garage", 109)]),
    ],
})

# ── imprimante ───────────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "imprimante", "titlu": "Cele mai bune imprimante 2026",
    "titlu_scurt": "Imprimante", "emoji": "🖨️", "culoare": "blue", "tag": "POPULAR",
    "descriere": "Top 5 imprimante pentru acasa si birou, evaluate pentru cost per pagina, calitate, viteza si conectivitate.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Epson EcoTank L3560", "EcoTank L3560", "ecotank", 1099, 9.4,
             {"Cost/pagina": 9.7, "Calitate": 9.2, "Viteza": 8.9, "Conectivitate": 9.3, "Pret/Calitate": 9.2},
             "Cel mai mic cost per pagina datorita rezervoarelor CISS",
             "EcoTank L3560 multifunctionala color cu rezervoare reincarcabile ofera cel mai mic cost per pagina din piata. Investitia initiala se amortizeaza rapid pentru cei care printeaza mult.",
             ["Cost per pagina minim", "Wi-Fi + scaner + copiator", "Rezervoare generoase", "Ideal volum mare"],
             ["Pret initial mai mare", "Viteza medie"],
             {"Tip": "Inkjet CISS multifunctional", "Functii": "Print/scan/copiere", "Conectivitate": "Wi-Fi, USB", "Color": "Da", "Cost/pagina": "Foarte mic"},
             [mag("emag.ro", "eMAG", 1099, True), mag("altex.ro", "Altex", 1149), mag("pcgarage.ro", "PC Garage", 1129)]),
        prod(2, "Cel mai bun raport pret", "green", "HP DeskJet 2720e", "DeskJet 2720e", "deskjet", 299, 9.0,
             {"Cost/pagina": 8.2, "Calitate": 8.8, "Viteza": 8.5, "Conectivitate": 9.0, "Pret/Calitate": 9.4},
             "Multifunctionala accesibila pentru uz ocazional acasa",
             "DeskJet 2720e este o multifunctionala inkjet ieftina, perfecta pentru printuri ocazionale acasa. Wi-Fi, scaner si HP+ cu luni de cerneala incluse via Instant Ink.",
             ["Pret mic", "Compacta", "Wi-Fi + scaner", "Luni de cerneala incluse"],
             ["Cost cartuse ridicat la volum", "Viteza modesta"],
             {"Tip": "Inkjet multifunctional", "Functii": "Print/scan/copiere", "Conectivitate": "Wi-Fi, USB", "Color": "Da"},
             [mag("emag.ro", "eMAG", 299, True), mag("altex.ro", "Altex", 319)]),
        prod(3, "Cea mai buna laser", "purple", "Brother HL-L2400DW", "HL-L2400DW", "brother-laser", 799, 9.2,
             {"Cost/pagina": 9.4, "Calitate": 9.3, "Viteza": 9.4, "Conectivitate": 9.0, "Pret/Calitate": 9.1},
             "Cea mai buna laser monocrom pentru documente",
             "HL-L2400DW este o laser monocrom rapida, cu duplex automat si Wi-Fi, ideala pentru cine printeaza multe documente text. Cost per pagina excelent si fiabilitate ridicata.",
             ["Viteza mare", "Duplex automat", "Cost/pagina mic la text", "Fiabila"],
             ["Doar alb-negru", "Fara scaner"],
             {"Tip": "Laser monocrom", "Viteza": "~30 ppm", "Duplex": "Automat", "Conectivitate": "Wi-Fi, USB", "Color": "Nu"},
             [mag("emag.ro", "eMAG", 799, True), mag("pcgarage.ro", "PC Garage", 829), mag("evomag.ro", "evoMAG", 819)]),
        prod(4, "Cea mai buna foto", "blue", "Canon PIXMA TS7450", "PIXMA TS7450", "pixma", 449, 8.9,
             {"Cost/pagina": 8.0, "Calitate": 9.4, "Viteza": 8.6, "Conectivitate": 9.1, "Pret/Calitate": 8.9},
             "Cele mai bune printuri foto color acasa",
             "PIXMA TS7450 exceleaza la printuri foto color cu detalii fine si culori bogate. Alegerea pentru cei care vor sa imprime fotografii de calitate acasa.",
             ["Calitate foto excelenta", "Wi-Fi + ecran tactil", "Compacta eleganta"],
             ["Cost cartuse foto ridicat", "Mai lenta pe foto"],
             {"Tip": "Inkjet foto multifunctional", "Functii": "Print/scan/copiere", "Conectivitate": "Wi-Fi, ecran tactil", "Color": "Da"},
             [mag("emag.ro", "eMAG", 449, True), mag("altex.ro", "Altex", 479)]),
        prod(5, "Cea mai buna buget", "gray", "Canon PIXMA TS3450", "PIXMA TS3450", "pixma-buget", 229, 8.3,
             {"Cost/pagina": 7.8, "Calitate": 8.4, "Viteza": 8.0, "Conectivitate": 8.6, "Pret/Calitate": 9.2},
             "Multifunctionala de baza sub 250 lei",
             "PIXMA TS3450 acopera nevoile esentiale de print, scanare si copiere acasa, cu Wi-Fi, la cel mai mic pret. Buna pentru utilizare ocazionala.",
             ["Pret foarte mic", "Wi-Fi + scaner", "Compacta"],
             ["Cost cartuse mare la volum", "Constructie simpla"],
             {"Tip": "Inkjet multifunctional", "Functii": "Print/scan/copiere", "Conectivitate": "Wi-Fi, USB", "Color": "Da"},
             [mag("emag.ro", "eMAG", 229, True), mag("altex.ro", "Altex", 249)]),
    ],
})

# ── camere-actiune ───────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "camere-actiune", "titlu": "Cele mai bune camere de actiune 2026",
    "titlu_scurt": "Camere actiune", "emoji": "📷", "culoare": "red", "tag": "TRENDING",
    "descriere": "Top 5 camere de actiune pentru sport, vlogging si aventura, evaluate pentru calitate video, stabilizare si rezistenta.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "GoPro HERO13 Black", "HERO13", "hero13", 1999, 9.5,
             {"Calitate video": 9.6, "Stabilizare": 9.6, "Rezistenta": 9.3, "Autonomie": 9.0, "Pret/Calitate": 9.0},
             "Cea mai buna camera de actiune all-round",
             "HERO13 Black ramane referinta categoriei: video 5.3K, stabilizare HyperSmooth excelenta si rezistenta la apa fara carcasa. Alegerea sigura pentru sport si aventura.",
             ["Stabilizare HyperSmooth de top", "Video 5.3K", "Waterproof 10m fara carcasa", "Ecosistem accesorii vast"],
             ["Pret ridicat", "Autonomie medie la 5.3K"],
             {"Rezolutie max": "5.3K60", "Stabilizare": "HyperSmooth 6", "Waterproof": "10m fara carcasa", "Ecran": "Fata + spate tactil"},
             [mag("emag.ro", "eMAG", 1999, True), mag("altex.ro", "Altex", 2099), mag("pcgarage.ro", "PC Garage", 2049)]),
        prod(2, "Cel mai bun raport pret", "green", "DJI Osmo Action 4", "Osmo Action 4", "osmo4", 1499, 9.3,
             {"Calitate video": 9.4, "Stabilizare": 9.4, "Rezistenta": 9.2, "Autonomie": 9.3, "Pret/Calitate": 9.4},
             "Cea mai buna alternativa la GoPro, autonomie mai buna",
             "Osmo Action 4 ofera senzor mare 1/1.3 inch, stabilizare RockSteady excelenta si autonomie superioara, la un pret mai bun decat GoPro. Excelenta pe lumina slaba.",
             ["Senzor mare, bun pe intuneric", "Autonomie excelenta", "Stabilizare RockSteady", "Pret competitiv"],
             ["Ecosistem accesorii mai mic", "Aplicatie ocazional capricioasa"],
             {"Rezolutie max": "4K120", "Senzor": "1/1.3 inch", "Stabilizare": "RockSteady 3.0", "Waterproof": "18m fara carcasa"},
             [mag("emag.ro", "eMAG", 1499, True), mag("altex.ro", "Altex", 1599), mag("evomag.ro", "evoMAG", 1549)]),
        prod(3, "Cea mai versatila", "purple", "Insta360 Ace Pro 2", "Ace Pro 2", "ace-pro2", 2299, 9.2,
             {"Calitate video": 9.5, "Stabilizare": 9.3, "Rezistenta": 9.0, "Autonomie": 9.2, "Pret/Calitate": 8.8},
             "Cea mai buna calitate de imagine si ecran flip",
             "Ace Pro 2, cu senzor Leica si ecran rabatabil, ofera cea mai buna calitate de imagine si functii AI utile pentru vlogging. Alegerea creatorilor de continut.",
             ["Calitate imagine de top (Leica)", "Ecran flip pentru vlog", "Functii AI utile", "Bun pe lumina slaba"],
             ["Pret premium", "Mai voluminoasa"],
             {"Rezolutie max": "8K30/4K120", "Senzor": "1/1.3 inch Leica", "Ecran": "Flip 2.5 inch", "Waterproof": "12m fara carcasa"},
             [mag("emag.ro", "eMAG", 2299, True), mag("pcgarage.ro", "PC Garage", 2399)]),
        prod(4, "Cea mai buna 360", "blue", "Insta360 X4", "X4", "insta-x4", 2599, 9.1,
             {"Calitate video": 9.3, "Stabilizare": 9.5, "Rezistenta": 9.0, "Autonomie": 9.0, "Pret/Calitate": 8.7},
             "Camera 360 pentru cadre imposibile si reframing",
             "X4 filmeaza 360° in 8K, permitand reframing-ul scenei dupa filmare si efecte spectaculoase de tip drona-pe-bat. Pentru creatorii care vor cadre unice.",
             ["Video 360 8K", "Reframing dupa filmare", "Efecte spectaculoase", "Stabilizare excelenta"],
             ["Editare mai complexa", "Pret ridicat"],
             {"Rezolutie max": "8K360", "Tip": "Camera 360", "Stabilizare": "FlowState", "Waterproof": "10m fara carcasa"},
             [mag("emag.ro", "eMAG", 2599, True), mag("altex.ro", "Altex", 2699)]),
        prod(5, "Cea mai buna buget", "gray", "AKASO Brave 8 / SJCAM", "Brave 8", "akaso", 599, 8.3,
             {"Calitate video": 8.2, "Stabilizare": 8.0, "Rezistenta": 8.4, "Autonomie": 8.3, "Pret/Calitate": 9.3},
             "Camera de actiune accesibila pentru incepatori",
             "Brave 8 ofera video 4K, stabilizare decenta si un pachet generos de accesorii incluse, la o fractiune din pretul brandurilor mari. Ideala pentru a incepe.",
             ["Pret foarte mic", "Accesorii incluse multe", "Video 4K", "Telecomanda inclusa"],
             ["Stabilizare sub GoPro/DJI", "Calitate medie pe intuneric"],
             {"Rezolutie max": "4K30", "Stabilizare": "Electronica de baza", "Waterproof": "Cu carcasa", "Extra": "Pachet accesorii inclus"},
             [mag("emag.ro", "eMAG", 599, True), mag("altex.ro", "Altex", 649)]),
    ],
})

# ── aer-conditionat ──────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "aer-conditionat", "titlu": "Cele mai bune aparate de aer conditionat 2026",
    "titlu_scurt": "Aer conditionat", "emoji": "❄️", "culoare": "blue", "tag": "SEZON",
    "descriere": "Top 5 aparate de aer conditionat inverter, evaluate pentru eficienta energetica, zgomot, racire si raport pret/calitate.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Daikin Sensira 12000 BTU", "Sensira FTXF35", "daikin", 2799, 9.4,
             {"Eficienta": 9.5, "Zgomot": 9.4, "Racire": 9.3, "Fiabilitate": 9.5, "Pret/Calitate": 9.0},
             "Cel mai bun echilibru eficienta-fiabilitate-zgomot",
             "Daikin Sensira 12000 BTU este referinta pentru o camera medie: clasa energetica A++, functionare silentioasa si fiabilitatea Daikin. Investitia sigura pe termen lung.",
             ["Foarte silentios", "Clasa A++ eficient", "Fiabilitate Daikin", "Racire rapida uniforma"],
             ["Pret peste medie", "Wi-Fi optional"],
             {"Capacitate": "12000 BTU", "Clasa energetica": "A++/A+", "Tip": "Inverter", "Zgomot": "~20 dB(A) min", "Suprafata": "~30 mp"},
             [mag("emag.ro", "eMAG", 2799, True), mag("altex.ro", "Altex", 2899), mag("evomag.ro", "evoMAG", 2849)]),
        prod(2, "Cel mai bun raport pret", "green", "Beko 12000 BTU inverter", "Beko BEVCSA", "beko-ac", 1799, 9.0,
             {"Eficienta": 8.9, "Zgomot": 8.7, "Racire": 9.0, "Fiabilitate": 8.8, "Pret/Calitate": 9.5},
             "Inverter eficient la cel mai bun pret pentru 30 mp",
             "Beko 12000 BTU ofera tehnologie inverter, clasa A++ si racire buna pentru o camera de 30 mp, la un pret excelent. Cel mai bun raport pret/performanta pentru bugete medii.",
             ["Pret excelent", "Inverter clasa A++", "Racire buna 30 mp", "Wi-Fi inclus la unele variante"],
             ["Mai zgomotos la viteza mare", "Finisaje simple"],
             {"Capacitate": "12000 BTU", "Clasa energetica": "A++", "Tip": "Inverter", "Suprafata": "~30 mp", "Wi-Fi": "Optional"},
             [mag("emag.ro", "eMAG", 1799, True), mag("altex.ro", "Altex", 1899), mag("flanco.ro", "Flanco", 1849)]),
        prod(3, "Cel mai silentios", "purple", "Mitsubishi 9000 BTU", "MSZ-HR25", "mitsubishi", 3199, 9.2,
             {"Eficienta": 9.3, "Zgomot": 9.6, "Racire": 9.1, "Fiabilitate": 9.4, "Pret/Calitate": 8.7},
             "Cel mai silentios, ideal pentru dormitor",
             "Mitsubishi 9000 BTU este alegerea pentru dormitor datorita functionarii extrem de silentioase si fiabilitatii legendare. Racire fina si consum redus pentru camere mici-medii.",
             ["Cel mai silentios din clasa", "Fiabilitate excelenta", "Eficient energetic", "Ideal dormitor"],
             ["Pret ridicat", "Capacitate mai mica 9000 BTU"],
             {"Capacitate": "9000 BTU", "Clasa energetica": "A++", "Tip": "Inverter", "Zgomot": "~19 dB(A)", "Suprafata": "~20 mp"},
             [mag("emag.ro", "eMAG", 3199, True), mag("altex.ro", "Altex", 3299)]),
        prod(4, "Cel mai bun pentru spatii mari", "blue", "LG DualCool 18000 BTU", "DualCool 18000", "lg-ac", 3499, 9.1,
             {"Eficienta": 9.2, "Zgomot": 9.0, "Racire": 9.5, "Fiabilitate": 9.0, "Pret/Calitate": 8.8},
             "Putere mare pentru living si spatii deschise",
             "LG DualCool 18000 BTU acopera living-uri si spatii deschise pana la ~45 mp, cu racire rapida, Wi-Fi si filtrare aer. Alegerea pentru camerele mari.",
             ["Putere mare 18000 BTU", "Racire rapida spatii mari", "Wi-Fi + filtrare", "Clasa A++"],
             ["Pret ridicat", "Consum mai mare la spatii mari"],
             {"Capacitate": "18000 BTU", "Clasa energetica": "A++", "Tip": "Inverter Dual", "Suprafata": "~45 mp", "Wi-Fi": "Da"},
             [mag("emag.ro", "eMAG", 3499, True), mag("altex.ro", "Altex", 3599), mag("flanco.ro", "Flanco", 3549)]),
        prod(5, "Cel mai bun buget", "gray", "Aer conditionat portabil 9000 BTU", "Portabil 9000", "ac-portabil", 1299, 8.3,
             {"Eficienta": 8.0, "Zgomot": 7.8, "Racire": 8.4, "Fiabilitate": 8.2, "Pret/Calitate": 9.1},
             "Solutie portabila fara montaj, sub 1300 lei",
             "Un aparat portabil de 9000 BTU este solutia pentru cei care nu pot monta split (chirie, restrictii): nu necesita instalare, se muta usor, racire decenta pentru camere mici.",
             ["Fara montaj/instalare", "Mobil intre camere", "Pret accesibil", "Ideal pentru chirie"],
             ["Mai zgomotos", "Eficienta sub split", "Ocupa spatiu pe podea"],
             {"Capacitate": "9000 BTU", "Tip": "Portabil monobloc", "Montaj": "Nu necesita", "Suprafata": "~20 mp"},
             [mag("emag.ro", "eMAG", 1299, True), mag("altex.ro", "Altex", 1349)]),
    ],
})

# ── aspiratoare-fara-fir ─────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "aspiratoare-fara-fir", "titlu": "Cele mai bune aspiratoare verticale fara fir 2026",
    "titlu_scurt": "Aspiratoare fara fir", "emoji": "🧹", "culoare": "purple", "tag": "POPULAR",
    "descriere": "Top 5 aspiratoare verticale fara fir, evaluate pentru putere de aspirare, autonomie, manevrabilitate si filtrare.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Dyson V12 Detect Slim", "V12 Detect", "dyson-v12", 2799, 9.5,
             {"Putere aspirare": 9.6, "Autonomie": 9.2, "Manevrabilitate": 9.5, "Filtrare": 9.5, "Pret/Calitate": 9.0},
             "Cel mai bun aspirator vertical fara fir all-round",
             "V12 Detect Slim combina putere mare de aspirare, laser care evidentiaza praful si ecran cu date in timp real, intr-un corp usor. Cea mai buna experienta de curatare fara fir.",
             ["Putere de aspirare excelenta", "Laser detectie praf", "Usor si manevrabil", "Filtrare HEPA"],
             ["Pret ridicat", "Recipient mediu"],
             {"Autonomie": "~60 min", "Filtrare": "HEPA sigilat", "Greutate": "~2.2 kg", "Recipient": "0.35 L", "Extra": "Laser + ecran LCD"},
             [mag("emag.ro", "eMAG", 2799, True), mag("altex.ro", "Altex", 2899), mag("flanco.ro", "Flanco", 2849)]),
        prod(2, "Cel mai bun raport pret", "green", "Rowenta X-Force Flex 9.60", "X-Force 9.60", "rowenta-x", 1299, 9.1,
             {"Putere aspirare": 9.0, "Autonomie": 9.3, "Manevrabilitate": 9.2, "Filtrare": 8.9, "Pret/Calitate": 9.5},
             "Aspirare puternica si autonomie mare la pret bun",
             "X-Force Flex 9.60 ofera autonomie de pana la 70 minute, tub flexibil pentru a curata sub mobila si putere buna, la jumatate din pretul Dyson. Cel mai bun mid-range.",
             ["Autonomie pana la 70 min", "Tub flexibil sub mobila", "Pret excelent", "Aspirare buna"],
             ["Filtrare sub Dyson", "Mai voluminos"],
             {"Autonomie": "~70 min", "Filtrare": "Multistrat", "Greutate": "~2.9 kg", "Recipient": "0.9 L", "Extra": "Tub flexibil"},
             [mag("emag.ro", "eMAG", 1299, True), mag("altex.ro", "Altex", 1399), mag("evomag.ro", "evoMAG", 1349)]),
        prod(3, "Cel mai premium", "purple", "Dyson V15 Detect", "V15 Detect", "dyson-v15", 3499, 9.4,
             {"Putere aspirare": 9.8, "Autonomie": 9.3, "Manevrabilitate": 9.3, "Filtrare": 9.6, "Pret/Calitate": 8.8},
             "Cea mai mare putere de aspirare si filtrare de top",
             "V15 Detect ofera cea mai mare putere de aspirare din gama, autonomie de 60 minute si filtrare avansata, ideal pentru case mari cu animale. Numararea particulelor pe ecran.",
             ["Putere de aspirare maxima", "Filtrare avansata", "Ideal pentru animale", "Autonomie 60 min"],
             ["Pret premium", "Greutate ceva mai mare"],
             {"Autonomie": "~60 min", "Filtrare": "HEPA sigilat", "Greutate": "~3 kg", "Recipient": "0.77 L", "Extra": "Laser + numarare particule"},
             [mag("emag.ro", "eMAG", 3499, True), mag("altex.ro", "Altex", 3599)]),
        prod(4, "Cel mai bun pentru animale", "blue", "Samsung Bespoke Jet AI", "Bespoke Jet", "samsung-jet", 2199, 9.0,
             {"Putere aspirare": 9.2, "Autonomie": 9.0, "Manevrabilitate": 9.1, "Filtrare": 9.3, "Pret/Calitate": 9.0},
             "Statie de golire automata, ideal pentru par de animale",
             "Bespoke Jet AI vine cu statie Clean Station care goleste automat recipientul, reducand contactul cu praful — ideal pentru alergici si case cu animale.",
             ["Golire automata igienica", "Buna pentru alergici", "Putere buna", "Filtrare multistrat"],
             ["Statia ocupa spatiu", "Pret peste medie"],
             {"Autonomie": "~60 min", "Filtrare": "Multistrat", "Greutate": "~2.5 kg", "Extra": "Statie golire automata"},
             [mag("emag.ro", "eMAG", 2199, True), mag("altex.ro", "Altex", 2299), mag("flanco.ro", "Flanco", 2249)]),
        prod(5, "Cel mai bun buget", "gray", "Tefal / Philips vertical fara fir", "Aqua Cordless", "tefal-cord", 599, 8.3,
             {"Putere aspirare": 8.0, "Autonomie": 8.2, "Manevrabilitate": 8.6, "Filtrare": 8.0, "Pret/Calitate": 9.3},
             "Aspirator vertical accesibil pentru intretinere zilnica",
             "Un aspirator vertical fara fir accesibil, potrivit pentru curatari rapide zilnice in apartamente mici. Usor si comod, la cel mai bun pret de intrare.",
             ["Pret foarte mic", "Usor si compact", "Bun pentru curatari rapide"],
             ["Putere si autonomie mai mici", "Recipient mic"],
             {"Autonomie": "~40 min", "Filtrare": "Standard", "Greutate": "~2.3 kg", "Recipient": "0.5 L"},
             [mag("emag.ro", "eMAG", 599, True), mag("altex.ro", "Altex", 649)]),
    ],
})

# ── boxe-bluetooth ───────────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "boxe-bluetooth", "titlu": "Cele mai bune boxe Bluetooth 2026",
    "titlu_scurt": "Boxe Bluetooth", "emoji": "🔊", "culoare": "red", "tag": "POPULAR",
    "descriere": "Top 5 boxe Bluetooth portabile, evaluate pentru calitate sunet, autonomie, rezistenta la apa si raport pret/calitate.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "JBL Charge 5", "Charge 5", "charge5", 599, 9.4,
             {"Sunet": 9.4, "Autonomie": 9.5, "Rezistenta": 9.3, "Portabilitate": 9.2, "Pret/Calitate": 9.2},
             "Cea mai echilibrata boxa portabila, cu powerbank",
             "JBL Charge 5 ofera sunet puternic, bass solid, 20 ore autonomie si rezistenta IP67. In plus, functioneaza ca powerbank pentru telefon. Cea mai sigura alegere portabila.",
             ["Sunet puternic cu bass bun", "Autonomie 20h", "IP67 apa+praf", "Functie powerbank"],
             ["Mai grea decat boxele mici", "Fara difuzor de inalte separat"],
             {"Autonomie": "~20h", "Rezistenta": "IP67", "Bluetooth": "5.1", "Extra": "Powerbank USB", "PartyBoost": "Da"},
             [mag("emag.ro", "eMAG", 599, True), mag("altex.ro", "Altex", 629), mag("pcgarage.ro", "PC Garage", 619)]),
        prod(2, "Cel mai bun raport pret", "green", "JBL Flip 6", "Flip 6", "flip6", 399, 9.1,
             {"Sunet": 9.0, "Autonomie": 9.0, "Rezistenta": 9.3, "Portabilitate": 9.5, "Pret/Calitate": 9.5},
             "Cel mai bun echilibru portabilitate-sunet sub 450 lei",
             "Flip 6 este compacta, rezistenta IP67 si suna excelent pentru dimensiunea ei, cu 12 ore autonomie. Cea mai buna boxa de cazat in rucsac pentru orice ocazie.",
             ["Compacta si portabila", "Sunet bun pentru marime", "IP67", "Pret excelent"],
             ["Bass mai modest ca Charge 5", "Fara powerbank"],
             {"Autonomie": "~12h", "Rezistenta": "IP67", "Bluetooth": "5.1", "PartyBoost": "Da"},
             [mag("emag.ro", "eMAG", 399, True), mag("altex.ro", "Altex", 429)]),
        prod(3, "Cea mai buna premium", "purple", "Bose SoundLink Flex 2", "SoundLink Flex 2", "bose-flex", 799, 9.3,
             {"Sunet": 9.6, "Autonomie": 9.0, "Rezistenta": 9.3, "Portabilitate": 9.2, "Pret/Calitate": 8.9},
             "Cel mai bun sunet dintr-o boxa portabila compacta",
             "SoundLink Flex 2 ofera semnatura sonora Bose — clar, echilibrat, surprinzator de amplu — intr-un corp rezistent IP67. Pentru cei care pun calitatea sunetului pe primul loc.",
             ["Calitate sunet superioara", "Clar la volum mare", "IP67 robusta", "Design premium"],
             ["Pret peste medie", "Autonomie 12h"],
             {"Autonomie": "~12h", "Rezistenta": "IP67", "Bluetooth": "5.3", "Extra": "Pozitionare automata PositionIQ"},
             [mag("emag.ro", "eMAG", 799, True), mag("altex.ro", "Altex", 849)]),
        prod(4, "Cea mai puternica", "blue", "JBL Xtreme 3 / PartyBox", "Xtreme 3", "xtreme3", 1299, 9.0,
             {"Sunet": 9.4, "Autonomie": 9.3, "Rezistenta": 9.0, "Portabilitate": 8.2, "Pret/Calitate": 8.9},
             "Sunet puternic pentru petreceri si exterior",
             "Xtreme 3 livreaza un sunet amplu, cu bass puternic, ideal pentru petreceri si spatii deschise. 15 ore autonomie, IP67 si curea de transport inclusa.",
             ["Sunet amplu pentru petreceri", "Bass puternic", "IP67", "Curea transport inclusa"],
             ["Voluminoasa si grea", "Mai putin portabila"],
             {"Autonomie": "~15h", "Rezistenta": "IP67", "Bluetooth": "5.1", "Extra": "Powerbank + curea"},
             [mag("emag.ro", "eMAG", 1299, True), mag("altex.ro", "Altex", 1349), mag("flanco.ro", "Flanco", 1329)]),
        prod(5, "Cea mai buna buget", "gray", "Anker Soundcore 3 / Tronsmart", "Soundcore 3", "soundcore3", 199, 8.4,
             {"Sunet": 8.3, "Autonomie": 9.0, "Rezistenta": 8.6, "Portabilitate": 9.2, "Pret/Calitate": 9.4},
             "Boxa portabila cu autonomie mare sub 220 lei",
             "Soundcore 3 ofera sunet curat, 24 ore autonomie si rezistenta IPX7, la un pret foarte mic. Cea mai buna boxa de buget pentru utilizare zilnica si calatorii.",
             ["Autonomie uriasa 24h", "Pret foarte mic", "IPX7 rezistenta apa", "Compacta"],
             ["Bass modest", "Fara putere pentru petreceri mari"],
             {"Autonomie": "~24h", "Rezistenta": "IPX7", "Bluetooth": "5.0", "Driver": "Titanium dual"},
             [mag("emag.ro", "eMAG", 199, True), mag("altex.ro", "Altex", 219)]),
    ],
})

# ── trotinete-electrice ──────────────────────────────────────────────────────
NEW_CATEGORIES.append({
    "slug": "trotinete-electrice", "titlu": "Cele mai bune trotinete electrice 2026",
    "titlu_scurt": "Trotinete electrice", "emoji": "🛴", "culoare": "yellow", "tag": "TRENDING",
    "descriere": "Top 5 trotinete electrice pentru oras si naveta, evaluate pentru autonomie, putere, siguranta si raport pret/calitate.",
    "produse": [
        prod(1, "Alegerea Redactiei", "orange", "Xiaomi Electric Scooter 4 Pro", "Scooter 4 Pro", "xiaomi-4pro", 2299, 9.4,
             {"Autonomie": 9.4, "Putere": 9.3, "Siguranta": 9.4, "Confort": 9.2, "Pret/Calitate": 9.2},
             "Cea mai echilibrata trotineta pentru naveta urbana",
             "Scooter 4 Pro ofera ~55 km autonomie, motor de 350W (varf 700W), frane duble si roti de 10 inch pentru confort. Cea mai sigura alegere pentru naveta zilnica in oras.",
             ["Autonomie ~55 km", "Roti 10 inch confortabile", "Frane duble sigure", "App + tablou de bord"],
             ["Greutate ~17 kg", "Pret peste medie"],
             {"Autonomie": "~55 km", "Motor": "350W (varf 700W)", "Viteza max": "25 km/h", "Roti": "10 inch", "Greutate": "~17 kg"},
             [mag("emag.ro", "eMAG", 2299, True), mag("altex.ro", "Altex", 2399), mag("quickmobile.ro", "QuickMobile", 2349)]),
        prod(2, "Cel mai bun raport pret", "green", "Xiaomi Electric Scooter 4 Lite", "Scooter 4 Lite", "xiaomi-4lite", 1499, 9.1,
             {"Autonomie": 9.0, "Putere": 8.8, "Siguranta": 9.0, "Confort": 8.9, "Pret/Calitate": 9.5},
             "Cea mai buna trotineta pentru incepatori sub 1500 lei",
             "Scooter 4 Lite ofera ~30 km autonomie, frane fiabile si roti tubeless, la cel mai bun pret. Ideala pentru navete scurte si pentru cei care incep cu trotineta electrica.",
             ["Pret excelent", "Roti tubeless anti-pana", "Usor de folosit", "App inclus"],
             ["Autonomie ~30 km", "Motor mai putin puternic la pante"],
             {"Autonomie": "~30 km", "Motor": "300W", "Viteza max": "25 km/h", "Roti": "10 inch tubeless", "Greutate": "~15 kg"},
             [mag("emag.ro", "eMAG", 1499, True), mag("altex.ro", "Altex", 1599)]),
        prod(3, "Cea mai performanta", "purple", "Segway Ninebot Max G2", "Max G2", "ninebot-g2", 3499, 9.3,
             {"Autonomie": 9.6, "Putere": 9.5, "Siguranta": 9.3, "Confort": 9.4, "Pret/Calitate": 8.8},
             "Autonomie si putere de top pentru navete lungi",
             "Ninebot Max G2 ofera pana la 70 km autonomie, suspensie fata-spate si motor puternic care urca pante usor. Alegerea pentru navete lungi si teren variat.",
             ["Autonomie pana la 70 km", "Suspensie fata-spate", "Urca pante bine", "Constructie robusta"],
             ["Greutate ~24 kg", "Pret ridicat"],
             {"Autonomie": "~70 km", "Motor": "450W (varf 1000W)", "Viteza max": "25 km/h", "Suspensie": "Fata + spate", "Greutate": "~24 kg"},
             [mag("emag.ro", "eMAG", 3499, True), mag("altex.ro", "Altex", 3599), mag("quickmobile.ro", "QuickMobile", 3549)]),
        prod(4, "Cea mai buna pentru oras", "blue", "Segway Ninebot E2 Plus", "Ninebot E2 Plus", "ninebot-e2", 1799, 8.9,
             {"Autonomie": 8.8, "Putere": 8.7, "Siguranta": 9.1, "Confort": 9.0, "Pret/Calitate": 9.1},
             "Compacta si usoara pentru oras si transport mixt",
             "Ninebot E2 Plus este usoara si compacta, ideala pentru a fi combinata cu transportul public. Autonomie ~35 km, pliere rapida si frane fiabile pentru oras.",
             ["Usoara si compacta", "Pliere rapida", "Buna pentru transport mixt", "Frane fiabile"],
             ["Autonomie medie", "Roti mai mici"],
             {"Autonomie": "~35 km", "Motor": "300W", "Viteza max": "25 km/h", "Roti": "9 inch", "Greutate": "~14 kg"},
             [mag("emag.ro", "eMAG", 1799, True), mag("altex.ro", "Altex", 1849)]),
        prod(5, "Cea mai buna buget", "gray", "Trotineta electrica entry-level", "Urban Lite", "urban-lite", 999, 8.2,
             {"Autonomie": 8.0, "Putere": 8.0, "Siguranta": 8.3, "Confort": 8.2, "Pret/Calitate": 9.2},
             "Intrare accesibila in mobilitate electrica, sub 1000 lei",
             "O trotineta entry-level potrivita pentru drumuri scurte si plate prin oras, la cel mai mic pret. Solutia accesibila pentru a testa mobilitatea electrica.",
             ["Pret foarte mic", "Usoara", "Buna pentru drumuri scurte plate"],
             ["Autonomie ~20 km", "Putere redusa la pante", "Frane simple"],
             {"Autonomie": "~20 km", "Motor": "250W", "Viteza max": "25 km/h", "Roti": "8.5 inch", "Greutate": "~12 kg"},
             [mag("emag.ro", "eMAG", 999, True), mag("altex.ro", "Altex", 1049)]),
    ],
})


def main():
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    existing = {c["slug"] for c in data["categorii"]}
    added = 0
    for cat in NEW_CATEGORIES:
        if cat["slug"] in existing:
            print(f"  skip (exista deja): {cat['slug']}")
            continue
        data["categorii"].append(cat)
        existing.add(cat["slug"])
        added += 1
        print(f"  + {cat['slug']} ({len(cat['produse'])} produse)")

    data["updated"] = "2026-06-15"
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\nGata. {added} categorii noi adaugate. Total: {len(data['categorii'])}")


if __name__ == "__main__":
    main()
