"""
Adaugă toate brandurile Impact.com în extra_merchants.json
Publisher ID AmCupon: 7761435 | Account ID: 7401119
Tracking link format: https://[brand].pxf.io/c/7761435/[id]
"""

import json, os

DATA_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "extra_merchants.json")
PUBLISHER_ID = "7761435"

# Format tracking link Impact.com
def impact_link(domain, campaign_id="1", promo_id="0"):
    return f"https://{domain}/c/{PUBLISHER_ID}/{campaign_id}/{promo_id}"

# Toate brandurile din Impact.com marketplace joined
IMPACT_BRANDS = [
    # ===== SOFTWARE / SAAS - comisioane mari =====
    {
        "magazin": "Surfshark",
        "url": "https://surfshark.com",
        "url_afiliat": "https://surfshark.com/?coupon=amcupon",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Surfshark_logo.svg/320px-Surfshark_logo.svg.png",
        "categorie": "Software & VPN",
        "categorie_slug": "electronics-itc",
        "comision": "40% + recurent",
        "scor_afiliere": 95,
        "descriere": "VPN premium cu politica no-logs, protectie avansata si viteze mari. Disponibil pe toate dispozitivele.",
    },
    {
        "magazin": "Hostinger",
        "url": "https://www.hostinger.ro",
        "url_afiliat": "https://www.hostinger.ro/?REFERRALCODE=AMCUPON",
        "logo_url": "https://www.hostinger.ro/assets/images/hostinger-logo.svg",
        "categorie": "Hosting & Domenii",
        "categorie_slug": "electronics-itc",
        "comision": "60%",
        "scor_afiliere": 95,
        "descriere": "Hosting web accesibil si rapid, ideal pentru site-uri WordPress, magazine online si bloguri.",
    },
    {
        "magazin": "Bitdefender",
        "url": "https://www.bitdefender.ro",
        "url_afiliat": "https://www.bitdefender.ro/affiliate/",
        "logo_url": "https://www.bitdefender.ro/img/bitdefender-logo.svg",
        "categorie": "Antivirus & Securitate",
        "categorie_slug": "electronics-itc",
        "comision": "20-40%",
        "scor_afiliere": 90,
        "descriere": "Antivirus romanesc de top, premiat mondial. Protejeaza PC, Mac, Android si iOS.",
    },
    {
        "magazin": "NortonLifeLock",
        "url": "https://us.norton.com",
        "url_afiliat": "https://us.norton.com/?utm_source=amcupon",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Norton_logo.svg/320px-Norton_logo.svg.png",
        "categorie": "Antivirus & Securitate",
        "categorie_slug": "electronics-itc",
        "comision": "25%",
        "scor_afiliere": 88,
        "descriere": "Norton 360 - protectie completa impotriva virusilor, ransomware si a furtului de identitate.",
    },
    {
        "magazin": "Shopify",
        "url": "https://www.shopify.com",
        "url_afiliat": "https://shopify.pxf.io/c/7761435/1/0",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Shopify_logo_2018.svg/320px-Shopify_logo_2018.svg.png",
        "categorie": "Ecommerce Platform",
        "categorie_slug": "online-mall",
        "comision": "$25-$150 per referral",
        "scor_afiliere": 92,
        "descriere": "Creeaza-ti magazinul online in minute. Shopify e cea mai populara platforma ecommerce din lume.",
    },
    {
        "magazin": "Coursera",
        "url": "https://www.coursera.org",
        "url_afiliat": "https://coursera.pxf.io/c/7761435/1/0",
        "logo_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Coursera-Logo_600x600.svg/320px-Coursera-Logo_600x600.svg.png",
        "categorie": "Educatie Online",
        "categorie_slug": "books",
        "comision": "15-45%",
        "scor_afiliere": 88,
        "descriere": "Cursuri online de la universitatile de top din lume: Google, IBM, Meta, Stanford si altele.",
    },
    {
        "magazin": "InVideo",
        "url": "https://invideo.io",
        "url_afiliat": "https://invideo.io/?ref=amcupon",
        "logo_url": "https://invideo.io/assets/images/invideo-logo.svg",
        "categorie": "Video & AI Tools",
        "categorie_slug": "electronics-itc",
        "comision": "25-50%",
        "scor_afiliere": 85,
        "descriere": "Creeaza videoclipuri profesionale cu AI in minute. Ideal pentru YouTube, TikTok si social media.",
    },
    {
        "magazin": "Envato Market",
        "url": "https://market.envato.com",
        "url_afiliat": "https://market.envato.com/?ref=amcupon",
        "logo_url": "https://envato.com/assets/img/envato-logo.svg",
        "categorie": "Teme & Pluginuri",
        "categorie_slug": "electronics-itc",
        "comision": "30%",
        "scor_afiliere": 87,
        "descriere": "Milioane de teme WordPress, pluginuri, fonturi, videoclipuri si resurse creative.",
    },
    {
        "magazin": "Blinkist",
        "url": "https://www.blinkist.com",
        "url_afiliat": "https://www.blinkist.com/invite/amcupon",
        "logo_url": "https://www.blinkist.com/images/og/og-homepage.png",
        "categorie": "Carti & Rezumate",
        "categorie_slug": "books",
        "comision": "20-25%",
        "scor_afiliere": 82,
        "descriere": "Rezumate ale celor mai bune carti de business si self-development in 15 minute.",
    },
    {
        "magazin": "HubSpot",
        "url": "https://www.hubspot.com",
        "url_afiliat": "https://www.hubspot.com/?ref=amcupon",
        "logo_url": "https://www.hubspot.com/hubfs/HubSpot_Logos/HubSpot-Inversed-Favicon.png",
        "categorie": "CRM & Marketing",
        "categorie_slug": "online-mall",
        "comision": "30%",
        "scor_afiliere": 84,
        "descriere": "CRM complet gratuit pentru marketing, vanzari si customer service. Folosit de 150.000+ companii.",
    },
    {
        "magazin": "DataCamp",
        "url": "https://www.datacamp.com",
        "url_afiliat": "https://www.datacamp.com/promo/amcupon",
        "logo_url": "https://www.datacamp.com/favicon.ico",
        "categorie": "Data Science",
        "categorie_slug": "books",
        "comision": "35%",
        "scor_afiliere": 80,
        "descriere": "Invata Data Science, Python, R, SQL si Machine Learning. Peste 350 cursuri interactive.",
    },
    {
        "magazin": "Magoosh",
        "url": "https://magoosh.com",
        "url_afiliat": "https://magoosh.com/?ref=amcupon",
        "logo_url": "https://magoosh.com/favicon.ico",
        "categorie": "Pregatire Examene",
        "categorie_slug": "books",
        "comision": "20%",
        "scor_afiliere": 75,
        "descriere": "Pregatire online pentru GRE, GMAT, IELTS, TOEFL, SAT. Lectii video si practica adaptiva.",
    },
    {
        "magazin": "O'Reilly Learning",
        "url": "https://www.oreilly.com",
        "url_afiliat": "https://www.oreilly.com/?ref=amcupon",
        "logo_url": "https://www.oreilly.com/favicon.ico",
        "categorie": "Carti Tehnice",
        "categorie_slug": "books",
        "comision": "20%",
        "scor_afiliere": 78,
        "descriere": "Biblioteca completa de carti si videocursuri tech: programare, AI, cloud, DevOps.",
    },
    {
        "magazin": "Upwork",
        "url": "https://www.upwork.com",
        "url_afiliat": "https://www.upwork.com/?ref=amcupon",
        "logo_url": "https://www.upwork.com/favicon.ico",
        "categorie": "Freelancing",
        "categorie_slug": "online-mall",
        "comision": "$150 per client nou",
        "scor_afiliere": 83,
        "descriere": "Cea mai mare platforma de freelancing. Gaseste freelanceri sau proiecte in orice domeniu.",
    },
    {
        "magazin": "Clean Email",
        "url": "https://clean.email",
        "url_afiliat": "https://clean.email/?ref=amcupon",
        "logo_url": "https://clean.email/favicon.ico",
        "categorie": "Productivitate",
        "categorie_slug": "electronics-itc",
        "comision": "30%",
        "scor_afiliere": 72,
        "descriere": "Curata inbox-ul Gmail sau Outlook in minute. Dezabonare in masa, stergere email-uri vechi.",
    },
    # ===== ELECTRONICS / GAMING =====
    {
        "magazin": "Banggood",
        "url": "https://www.banggood.com",
        "url_afiliat": "https://www.banggood.com/affiliate.html?ref=amcupon",
        "logo_url": "https://img.staticbg.com/images/footer/banggood_logo_white.png",
        "categorie": "Electronice & Gadgeturi",
        "categorie_slug": "electronics-itc",
        "comision": "5-12%",
        "scor_afiliere": 85,
        "descriere": "Gadgeturi, electronice si accesorii la preturi mici direct din China. Livrare internationala.",
    },
    {
        "magazin": "Logitech",
        "url": "https://www.logitech.com",
        "url_afiliat": "https://www.logitech.com/?ref=amcupon",
        "logo_url": "https://www.logitech.com/assets/65376/logitech-bug-logo.png",
        "categorie": "Periferice Gaming",
        "categorie_slug": "electronics-itc",
        "comision": "4-8%",
        "scor_afiliere": 85,
        "descriere": "Mouse, tastatura, webcam si casti de la cel mai popular brand de periferice din lume.",
    },
    {
        "magazin": "Razer",
        "url": "https://www.razer.com",
        "url_afiliat": "https://www.razer.com/?ref=amcupon",
        "logo_url": "https://assets.razerzone.com/eeimages/social-pages/razer-logo-og.png",
        "categorie": "Gaming",
        "categorie_slug": "games",
        "comision": "5-10%",
        "scor_afiliere": 83,
        "descriere": "Periferice gaming premium: mouse, tastatura, casti, laptop gaming si accesorii Razer.",
    },
    {
        "magazin": "Lenovo",
        "url": "https://www.lenovo.com/ro",
        "url_afiliat": "https://www.lenovo.com/ro/?ref=amcupon",
        "logo_url": "https://www.lenovo.com/medias/lenovo-logo.png",
        "categorie": "Laptopuri & PC",
        "categorie_slug": "electronics-itc",
        "comision": "4-8%",
        "scor_afiliere": 87,
        "descriere": "Laptopuri, tablete si PC-uri Lenovo. ThinkPad, IdeaPad, Legion Gaming la preturi competitive.",
    },
    {
        "magazin": "UPERFECT",
        "url": "https://www.uperfectmonitor.com",
        "url_afiliat": "https://www.uperfectmonitor.com/?ref=amcupon",
        "logo_url": "https://www.uperfectmonitor.com/favicon.ico",
        "categorie": "Monitoare Portabile",
        "categorie_slug": "electronics-itc",
        "comision": "10%",
        "scor_afiliere": 75,
        "descriere": "Monitoare portabile 4K pentru laptop, telefon si consola. Perfecte pentru lucru remote.",
    },
    {
        "magazin": "Skylum",
        "url": "https://skylum.com",
        "url_afiliat": "https://skylum.com/?ref=amcupon",
        "logo_url": "https://skylum.com/favicon.ico",
        "categorie": "Editare Foto",
        "categorie_slug": "electronics-itc",
        "comision": "20-30%",
        "scor_afiliere": 76,
        "descriere": "Luminar Neo - editare foto cu AI. Cel mai intuitiv software pentru fotografi.",
    },
    {
        "magazin": "Mailbird",
        "url": "https://www.getmailbird.com",
        "url_afiliat": "https://www.getmailbird.com/?ref=amcupon",
        "logo_url": "https://www.getmailbird.com/favicon.ico",
        "categorie": "Email Client",
        "categorie_slug": "electronics-itc",
        "comision": "25%",
        "scor_afiliere": 70,
        "descriere": "Client email Windows elegant, cu integrari pentru Gmail, Outlook, Slack si altele.",
    },
    {
        "magazin": "Vecteezy",
        "url": "https://www.vecteezy.com",
        "url_afiliat": "https://www.vecteezy.com/?ref=amcupon",
        "logo_url": "https://www.vecteezy.com/favicon.ico",
        "categorie": "Vectori & Design",
        "categorie_slug": "electronics-itc",
        "comision": "20%",
        "scor_afiliere": 70,
        "descriere": "Milioane de vectori, ilustratii si imagini stock gratuite si premium pentru designeri.",
    },
    # ===== FASHION / LIFESTYLE =====
    {
        "magazin": "DHgate",
        "url": "https://www.dhgate.com",
        "url_afiliat": "https://www.dhgate.com/?ref=amcupon",
        "logo_url": "https://www.dhgate.com/favicon.ico",
        "categorie": "Fashion & General",
        "categorie_slug": "online-mall",
        "comision": "2-50%",
        "scor_afiliere": 82,
        "descriere": "Marketplace cu milioane de produse la preturi angro direct din China. Haine, gadgeturi, bijuterii.",
    },
    {
        "magazin": "StockX",
        "url": "https://stockx.com",
        "url_afiliat": "https://stockx.com/?ref=amcupon",
        "logo_url": "https://stockx.com/favicon.ico",
        "categorie": "Sneakers & Streetwear",
        "categorie_slug": "fashion",
        "comision": "3-8%",
        "scor_afiliere": 80,
        "descriere": "Cumparati si vindeti sneakers, haine streetwear si accesorii autentice. Verificare garantata.",
    },
    {
        "magazin": "Crocs",
        "url": "https://www.crocs.com",
        "url_afiliat": "https://www.crocs.com/?ref=amcupon",
        "logo_url": "https://www.crocs.com/favicon.ico",
        "categorie": "Incaltaminte",
        "categorie_slug": "fashion",
        "comision": "5-10%",
        "scor_afiliere": 78,
        "descriere": "Incaltaminte Crocs confortabila si colorata. Clasicii si noile colectii cu Jibbitz.",
    },
    {
        "magazin": "Cuyana",
        "url": "https://www.cuyana.com",
        "url_afiliat": "https://www.cuyana.com/?ref=amcupon",
        "logo_url": "https://www.cuyana.com/favicon.ico",
        "categorie": "Fashion Feminin",
        "categorie_slug": "fashion",
        "comision": "8-12%",
        "scor_afiliere": 72,
        "descriere": "Haine si genti din materiale sustenabile de calitate premium pentru femei.",
    },
    {
        "magazin": "Vivaia",
        "url": "https://vivaia.com",
        "url_afiliat": "https://vivaia.com/?ref=amcupon",
        "logo_url": "https://vivaia.com/favicon.ico",
        "categorie": "Pantofi Sustenabili",
        "categorie_slug": "fashion",
        "comision": "10-15%",
        "scor_afiliere": 70,
        "descriere": "Pantofi confortabili din materiale reciclate. Eco-friendly si stilati.",
    },
    {
        "magazin": "Cariloha",
        "url": "https://www.cariloha.com",
        "url_afiliat": "https://www.cariloha.com/?ref=amcupon",
        "logo_url": "https://www.cariloha.com/favicon.ico",
        "categorie": "Imbracaminte Bambus",
        "categorie_slug": "fashion",
        "comision": "6%",
        "scor_afiliere": 65,
        "descriere": "Haine, lenjerie de pat si prosoape din bambus organic. Extrem de moi si sustenabile.",
    },
    # ===== CALATORIE / TURISM =====
    {
        "magazin": "KKday",
        "url": "https://www.kkday.com",
        "url_afiliat": "https://www.kkday.com/?ref=amcupon",
        "logo_url": "https://www.kkday.com/favicon.ico",
        "categorie": "Turism & Activitati",
        "categorie_slug": "gifts-flowers",
        "comision": "2-5%",
        "scor_afiliere": 72,
        "descriere": "Activitati, tururi si experiente de calatorie in toata lumea. Rezervari instant.",
    },
    {
        "magazin": "Omio",
        "url": "https://www.omio.com",
        "url_afiliat": "https://www.omio.com/?ref=amcupon",
        "logo_url": "https://www.omio.com/favicon.ico",
        "categorie": "Transport & Calatorii",
        "categorie_slug": "gifts-flowers",
        "comision": "3-5%",
        "scor_afiliere": 75,
        "descriere": "Cauta si rezerva tren, autobuz si avion in Europa si America. Cel mai simplu mod de a calatori.",
    },
    {
        "magazin": "Ticket Liquidator",
        "url": "https://www.ticketliquidator.com",
        "url_afiliat": "https://www.ticketliquidator.com/?ref=amcupon",
        "logo_url": "https://www.ticketliquidator.com/favicon.ico",
        "categorie": "Bilete Evenimente",
        "categorie_slug": "gifts-flowers",
        "comision": "5-8%",
        "scor_afiliere": 70,
        "descriere": "Bilete pentru concerte, sporturi si evenimente. Stocuri garantate si preturi competitive.",
    },
    {
        "magazin": "Wyndham Rewards",
        "url": "https://www.wyndhamhotels.com",
        "url_afiliat": "https://www.wyndhamhotels.com/?ref=amcupon",
        "logo_url": "https://www.wyndhamhotels.com/favicon.ico",
        "categorie": "Hoteluri",
        "categorie_slug": "gifts-flowers",
        "comision": "3-5%",
        "scor_afiliere": 68,
        "descriere": "Peste 9.000 de hoteluri Wyndham in toata lumea. Puncte de fidelitate si oferte exclusive.",
    },
    # ===== HOSTING & DOMENII =====
    {
        "magazin": "Bluehost",
        "url": "https://www.bluehost.com",
        "url_afiliat": "https://www.bluehost.com/track/amcupon",
        "logo_url": "https://www.bluehost.com/favicon.ico",
        "categorie": "Hosting WordPress",
        "categorie_slug": "electronics-itc",
        "comision": "$65-$130 per sale",
        "scor_afiliere": 85,
        "descriere": "Hosting WordPress recomandat oficial. Domeniu gratuit, SSL gratuit si instalare WordPress 1-click.",
    },
    {
        "magazin": "Domain.com",
        "url": "https://www.domain.com",
        "url_afiliat": "https://www.domain.com/?ref=amcupon",
        "logo_url": "https://www.domain.com/favicon.ico",
        "categorie": "Domenii Web",
        "categorie_slug": "electronics-itc",
        "comision": "10-20%",
        "scor_afiliere": 75,
        "descriere": "Inregistreaza domenii .ro, .com, .net la preturi mici. Include email si hosting.",
    },
    # ===== SPORT & SANATATE =====
    {
        "magazin": "Muc-Off",
        "url": "https://muc-off.com",
        "url_afiliat": "https://muc-off.com/?ref=amcupon",
        "logo_url": "https://muc-off.com/favicon.ico",
        "categorie": "Biciclete & MTB",
        "categorie_slug": "sports-outdoors",
        "comision": "10%",
        "scor_afiliere": 72,
        "descriere": "Produse de curatenie si intretinere pentru biciclete, moto si masini. Brand profesional UK.",
    },
    {
        "magazin": "Tempo",
        "url": "https://tempo.fit",
        "url_afiliat": "https://tempo.fit/?ref=amcupon",
        "logo_url": "https://tempo.fit/favicon.ico",
        "categorie": "Fitness & Sport",
        "categorie_slug": "sports-outdoors",
        "comision": "8-15%",
        "scor_afiliere": 70,
        "descriere": "Echipamente fitness inteligente cu AI coaching. Antrenament personalizat acasa.",
    },
    {
        "magazin": "SportsLine",
        "url": "https://www.sportsline.com",
        "url_afiliat": "https://www.sportsline.com/?ref=amcupon",
        "logo_url": "https://www.sportsline.com/favicon.ico",
        "categorie": "Pariuri & Sport",
        "categorie_slug": "sports-outdoors",
        "comision": "25-40%",
        "scor_afiliere": 70,
        "descriere": "Predictii sportive bazate pe AI si simulari. Basketball, fotbal american, baseball.",
    },
    {
        "magazin": "Intego",
        "url": "https://www.intego.com",
        "url_afiliat": "https://www.intego.com/?ref=amcupon",
        "logo_url": "https://www.intego.com/favicon.ico",
        "categorie": "Securitate Mac",
        "categorie_slug": "electronics-itc",
        "comision": "25-40%",
        "scor_afiliere": 73,
        "descriere": "Cel mai bun antivirus pentru Mac. Protejeaza MacBook si iMac de virusi si malware.",
    },
    {
        "magazin": "Nelio",
        "url": "https://neliosoftware.com",
        "url_afiliat": "https://neliosoftware.com/?ref=amcupon",
        "logo_url": "https://neliosoftware.com/favicon.ico",
        "categorie": "WordPress Tools",
        "categorie_slug": "electronics-itc",
        "comision": "30%",
        "scor_afiliere": 65,
        "descriere": "Pluginuri WordPress premium: A/B testing, heatmaps, content calendars si altele.",
    },
    {
        "magazin": "BdThemes",
        "url": "https://bdthemes.com",
        "url_afiliat": "https://bdthemes.com/?ref=amcupon",
        "logo_url": "https://bdthemes.com/favicon.ico",
        "categorie": "Teme WordPress",
        "categorie_slug": "electronics-itc",
        "comision": "30%",
        "scor_afiliere": 68,
        "descriere": "Teme si pluginuri Elementor premium. Pachete complete pentru orice tip de site.",
    },
    {
        "magazin": "Meta Box",
        "url": "https://metabox.io",
        "url_afiliat": "https://metabox.io/?ref=amcupon",
        "logo_url": "https://metabox.io/favicon.ico",
        "categorie": "WordPress Custom Fields",
        "categorie_slug": "electronics-itc",
        "comision": "30%",
        "scor_afiliere": 65,
        "descriere": "Plugin WordPress pentru campuri personalizate si Custom Post Types. 500.000+ utilizatori.",
    },
    {
        "magazin": "Debutify",
        "url": "https://debutify.com",
        "url_afiliat": "https://debutify.com/?ref=amcupon",
        "logo_url": "https://debutify.com/favicon.ico",
        "categorie": "Teme Shopify",
        "categorie_slug": "electronics-itc",
        "comision": "20-40%",
        "scor_afiliere": 70,
        "descriere": "Tema Shopify #1 pentru conversii. Include sute de add-ons pentru optimizare vanzari.",
    },
    {
        "magazin": "Alamy",
        "url": "https://www.alamy.com",
        "url_afiliat": "https://www.alamy.com/?ref=amcupon",
        "logo_url": "https://www.alamy.com/favicon.ico",
        "categorie": "Stock Photos",
        "categorie_slug": "online-mall",
        "comision": "10-20%",
        "scor_afiliere": 72,
        "descriere": "Cea mai mare biblioteca de stock photos si imagini editoriale. 350+ milioane imagini.",
    },
    {
        "magazin": "Sorare",
        "url": "https://sorare.com",
        "url_afiliat": "https://sorare.com/?ref=amcupon",
        "logo_url": "https://sorare.com/favicon.ico",
        "categorie": "Fantasy Sports NFT",
        "categorie_slug": "games",
        "comision": "10-15%",
        "scor_afiliere": 65,
        "descriere": "Fantasy football cu carduri digitale (NFT) ale jucatorilor reali. Castiga premii saptamanal.",
    },
    {
        "magazin": "Rumpl",
        "url": "https://rumpl.com",
        "url_afiliat": "https://rumpl.com/?ref=amcupon",
        "logo_url": "https://rumpl.com/favicon.ico",
        "categorie": "Outdoor & Camping",
        "categorie_slug": "sports-outdoors",
        "comision": "8-12%",
        "scor_afiliere": 65,
        "descriere": "Paturi si saci de dormit tehnici pentru outdoor si calatorie. Materiale reciclate.",
    },
    {
        "magazin": "TS Plus",
        "url": "https://terminalserviceplus.com",
        "url_afiliat": "https://terminalserviceplus.com/?ref=amcupon",
        "logo_url": "https://terminalserviceplus.com/favicon.ico",
        "categorie": "Remote Access Software",
        "categorie_slug": "electronics-itc",
        "comision": "30%",
        "scor_afiliere": 70,
        "descriere": "Software acces remote si publicare aplicatii Windows. Alternativa la Citrix si RDS.",
    },
    {
        "magazin": "British Council",
        "url": "https://www.britishcouncil.org",
        "url_afiliat": "https://www.britishcouncil.org/?ref=amcupon",
        "logo_url": "https://www.britishcouncil.org/favicon.ico",
        "categorie": "Invatare Engleza",
        "categorie_slug": "books",
        "comision": "5-10%",
        "scor_afiliere": 72,
        "descriere": "Cursuri de engleza online de la British Council. Certificate recunoscute international.",
    },
    {
        "magazin": "Treezy",
        "url": "https://www.treezy.de",
        "url_afiliat": "https://www.treezy.de/?ref=amcupon",
        "logo_url": "https://www.treezy.de/favicon.ico",
        "categorie": "Brazi Artificiali",
        "categorie_slug": "home-garden",
        "comision": "8-12%",
        "scor_afiliere": 62,
        "descriere": "Brazi de Craciun artificiali premium din Germania. Realist, durabil, fara intretinere.",
    },
    {
        "magazin": "Revolut Business",
        "url": "https://www.revolut.com/business",
        "url_afiliat": "https://www.revolut.com/business/?ref=amcupon",
        "logo_url": "https://www.revolut.com/favicon.ico",
        "categorie": "Banking Digital",
        "categorie_slug": "online-mall",
        "comision": "$50-200 per referral",
        "scor_afiliere": 88,
        "descriere": "Cont business digital Revolut. Platesti in orice valuta fara comision, carduri virtuale, API.",
    },
    {
        "magazin": "Uphold",
        "url": "https://uphold.com",
        "url_afiliat": "https://uphold.com/?ref=amcupon",
        "logo_url": "https://uphold.com/favicon.ico",
        "categorie": "Crypto & Finance",
        "categorie_slug": "online-mall",
        "comision": "20-30%",
        "scor_afiliere": 72,
        "descriere": "Platforma crypto cu 250+ monede digitale, metale pretioase si actiuni. Simplu si sigur.",
    },
    {
        "magazin": "Termly",
        "url": "https://termly.io",
        "url_afiliat": "https://termly.io/?ref=amcupon",
        "logo_url": "https://termly.io/favicon.ico",
        "categorie": "Politici GDPR",
        "categorie_slug": "online-mall",
        "comision": "25%",
        "scor_afiliere": 68,
        "descriere": "Generator de politici de confidentialitate, GDPR, termeni si conditii pentru site-uri.",
    },
    {
        "magazin": "Martinic Audio",
        "url": "https://www.martinic.com",
        "url_afiliat": "https://www.martinic.com/?ref=amcupon",
        "logo_url": "https://www.martinic.com/favicon.ico",
        "categorie": "Software Muzica",
        "categorie_slug": "online-mall",
        "comision": "30%",
        "scor_afiliere": 62,
        "descriere": "Plugin-uri audio si sintetizatoare virtuale pentru productie muzicala profesionala.",
    },
    {
        "magazin": "Wildbird",
        "url": "https://wildbird.com",
        "url_afiliat": "https://wildbird.com/?ref=amcupon",
        "logo_url": "https://wildbird.com/favicon.ico",
        "categorie": "Babywearing",
        "categorie_slug": "babies-kids-toys",
        "comision": "8-12%",
        "scor_afiliere": 60,
        "descriere": "Esarfe si purti pentru bebelusi. Designuri frumoase si confortabile pentru parinti.",
    },
    {
        "magazin": "NuLeaf Naturals",
        "url": "https://nuleafnaturals.com",
        "url_afiliat": "https://nuleafnaturals.com/?ref=amcupon",
        "logo_url": "https://nuleafnaturals.com/favicon.ico",
        "categorie": "CBD & Wellness",
        "categorie_slug": "health-personal-care",
        "comision": "20-30%",
        "scor_afiliere": 65,
        "descriere": "Uleiuri CBD organice de cea mai inalta calitate. Testate de laboratoare independente.",
    },
    {
        "magazin": "Anantara Hotels",
        "url": "https://www.anantara.com",
        "url_afiliat": "https://www.anantara.com/?ref=amcupon",
        "logo_url": "https://www.anantara.com/favicon.ico",
        "categorie": "Hoteluri Lux",
        "categorie_slug": "gifts-flowers",
        "comision": "3-5%",
        "scor_afiliere": 68,
        "descriere": "Hoteluri si resorturi de lux in Asia, Orientul Mijlociu si Africa. Experiente unice.",
    },
    {
        "magazin": "Maxbone",
        "url": "https://www.maxbone.com",
        "url_afiliat": "https://www.maxbone.com/?ref=amcupon",
        "logo_url": "https://www.maxbone.com/favicon.ico",
        "categorie": "Accesorii Animale",
        "categorie_slug": "pet-supplies",
        "comision": "8-12%",
        "scor_afiliere": 65,
        "descriere": "Colectie premium de accesorii si haine pentru caini. Design minimalist si materiale eco.",
    },
    {
        "magazin": "LARQ",
        "url": "https://www.livelarq.com",
        "url_afiliat": "https://www.livelarq.com/?ref=amcupon",
        "logo_url": "https://www.livelarq.com/favicon.ico",
        "categorie": "Sticle Apa Smart",
        "categorie_slug": "sports-outdoors",
        "comision": "8%",
        "scor_afiliere": 65,
        "descriere": "Sticle de apa cu purificator UV-C integrat. Sterileaza apa automat la 60 secunde.",
    },
    {
        "magazin": "Prop Money Inc",
        "url": "https://propmoney.com",
        "url_afiliat": "https://propmoney.com/?ref=amcupon",
        "logo_url": "https://propmoney.com/favicon.ico",
        "categorie": "Prop Money",
        "categorie_slug": "online-mall",
        "comision": "3%",
        "scor_afiliere": 45,
        "descriere": "Bancnote prop pentru filme, videoclipuri muzicale si evenimente. 100% legal.",
    },
    {
        "magazin": "Arkuda Digital",
        "url": "https://www.arkuda.digital",
        "url_afiliat": "https://www.arkuda.digital/?ref=amcupon",
        "logo_url": "https://www.arkuda.digital/favicon.ico",
        "categorie": "Streaming Apps",
        "categorie_slug": "online-mall",
        "comision": "0.01%",
        "scor_afiliere": 20,
        "descriere": "Aplicatii de streaming pentru media players. IPTV si acces la continut digital.",
    },
]

# Template entry complet
def make_entry(b):
    return {
        "magazin": b["magazin"],
        "url": b["url"],
        "url_afiliat": b.get("url_afiliat", b["url"]),
        "logo_url": b.get("logo_url", ""),
        "categorie": b.get("categorie", "Diverse"),
        "categorie_slug": b.get("categorie_slug", "online-mall"),
        "comision": b.get("comision", "Variabil"),
        "rank": None,
        "scor_afiliere": b.get("scor_afiliere", 50),
        "scor_final": b.get("scor_afiliere", 50),
        "prioritate": "featured" if b.get("scor_afiliere", 50) >= 85 else "standard",
        "canal_recomandat": "Content, SEO, Social",
        "sales_number": 0,
        "trend": 0,
        "are_promotie": False,
        "cod_cupon": False,
        "zile_ramase": 0,
        "promotii": [],
        "folosit_de": 0,
        "procent_succes": 85,
        "exclusiv": False,
        "platforma": "impact",
        "descriere": b.get("descriere", ""),
    }

def main():
    with open(DATA_PATH, "r", encoding="utf-8") as f:
        existing = json.load(f)

    existing_names = {e["magazin"].lower() for e in existing}
    added = 0

    for b in IMPACT_BRANDS:
        if b["magazin"].lower() not in existing_names:
            existing.append(make_entry(b))
            existing_names.add(b["magazin"].lower())
            added += 1
        else:
            print(f"  Skip (exista deja): {b['magazin']}")

    with open(DATA_PATH, "w", encoding="utf-8") as f:
        json.dump(existing, f, ensure_ascii=False, indent=2)

    print(f"\nGata! {added} branduri Impact.com adaugate. Total: {len(existing)}")

if __name__ == "__main__":
    main()
